/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         policyID: "in consequat",
 *         ruleParams: {
 *             name: "",
 *             ID: "ea labore i",
 *             ruleExpression: "ullamco mollit est consectetur aliquip",
 *             columnRuleParams: {
 *                 vaultID: "laboris p",
 *                 columns: ["esse", "et Lorem", "do id"],
 *                 action: "NONE_ACTION",
 *                 effect: "NONE_EFFECT",
 *                 rowFilter: "Lorem",
 *                 redaction: "ullamco Excepteur incididunt",
 *                 actions: ["NONE_ACTION", "NONE_ACTION", "NONE_ACTION"]
 *             },
 *             tableRuleParams: {
 *                 vaultID: "veli",
 *                 tableName: "tempor commodo",
 *                 action: "NONE_ACTION",
 *                 effect: "NONE_EFFECT",
 *                 rowFilter: "Ut in proident amet dolor",
 *                 actions: ["NONE_ACTION", "NONE_ACTION", "NONE_ACTION"]
 *             },
 *             columnGroupRuleParams: {
 *                 vaultID: "sint",
 *                 columnGroups: ["do", "nostrud occaecat", "irure in aute fugiat Lorem"],
 *                 action: "NONE_ACTION",
 *                 effect: "NONE_EFFECT",
 *                 rowFilter: "irure voluptate",
 *                 redaction: "Lorem incididunt",
 *                 actions: ["NONE_ACTION", "NONE_ACTION", "NONE_ACTION"]
 *             }
 *         }
 *     }
 */
export interface PolicyAuthoringServiceUpdateRuleBody {
    /** ID of the policy that contains the rule. */
    policyID?: string;
    ruleParams?: Skyflow.V1RuleParams;
}
