/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         ID: "id ut elit irure",
 *         roleIDs: ["aute", "anim incididunt ut adipisicing", "culpa irure"],
 *         members: [{
 *                 ID: "ullamco Duis est in",
 *                 type: "NONE",
 *                 name: "incididunt",
 *                 email: "vol",
 *                 status: "NONE"
 *             }, {
 *                 ID: "commodo aliquip",
 *                 type: "NONE",
 *                 name: "eu nostrud",
 *                 email: "cupidatat Excepteur nisi do in",
 *                 status: "NONE"
 *             }, {
 *                 ID: "dolor proident adipisicing ullamco",
 *                 type: "NONE",
 *                 name: "ullamco cupidatat Lore",
 *                 email: "ea anim des",
 *                 status: "NONE"
 *             }],
 *         exceptions: [{
 *                 ID: "ex dolore fugiat",
 *                 type: "NONE",
 *                 name: "vol",
 *                 email: "id consequat",
 *                 status: "NONE"
 *             }, {
 *                 ID: "do id eu",
 *                 type: "NONE",
 *                 name: "do ",
 *                 email: "tempo",
 *                 status: "NONE"
 *             }, {
 *                 ID: "Ut deserunt officia",
 *                 type: "NONE",
 *                 name: "eiusmod sunt ullamco dolore",
 *                 email: "Duis esse Excepteur non dolore",
 *                 status: "NONE"
 *             }]
 *     }
 */
export interface V1AssignPolicyRequest {
    /** ID of the policy. */
    ID?: string;
    /** IDs of the roles. */
    roleIDs?: string[];
    members?: Skyflow.V1Member[];
    exceptions?: Skyflow.V1Member[];
}
