/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         fetchMetadataOnly: true
 *     }
 */
export interface ObjectVaultServiceGetObjectVaultRequest {
    /**
     * If `true`, only returns the vault ID, name, description, status, namespace, and basic audit metadata.
     */
    fetchMetadataOnly?: boolean;
}
