/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface TokenExchangeServiceUpdateStsConfigBody {
    name?: string;
    description?: string;
    issuer?: string;
    /** Public keys as JWK endpoint */
    publicKeyJWKURI?: string;
    contextClaims?: string[];
    /** list of service account IDs; */
    serviceAccountIDs?: string[];
}
