/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RecordServiceBulkGetRecordRequestOrderBy = "ASCENDING" | "DESCENDING" | "NONE";
export const RecordServiceBulkGetRecordRequestOrderBy = {
    Ascending: "ASCENDING",
    Descending: "DESCENDING",
    None: "NONE",
} as const;
