/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RecordServiceBulkGetRecordRequestRedaction = "DEFAULT" | "REDACTED" | "MASKED" | "PLAIN_TEXT";
export const RecordServiceBulkGetRecordRequestRedaction = {
    Default: "DEFAULT",
    Redacted: "REDACTED",
    Masked: "MASKED",
    PlainText: "PLAIN_TEXT",
} as const;
