/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         publicKeyType: "TYPE_NONE"
 *     }
 */
export interface ServiceAccountServiceGetServiceAccountKeyRequest {
    /**
     * Output format of the public key.
     */
    publicKeyType?: Skyflow.ServiceAccountServiceGetServiceAccountKeyRequestPublicKeyType;
}
