/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         offset: "offset",
 *         limit: "limit",
 *         name: "name",
 *         status: "NONE",
 *         "resource.ID": "resource.ID",
 *         "resource.type": "NONE",
 *         "resource.name": "resource.name",
 *         "resource.namespace": "resource.namespace",
 *         "resource.description": "resource.description",
 *         "resource.status": "NONE",
 *         "resource.displayName": "resource.displayName",
 *         depth: "depth"
 *     }
 */
export interface ServiceAccountServiceListServiceAccountsRequest {
    /**
     * Record position at with to start returning results.
     */
    offset?: string;
    /**
     * Number of results to return.
     */
    limit?: string;
    /**
     * ID of the account that the service account belongs to. Defaults to the account specified in the `X-Skyflow-Account-ID` header.
     */
    accountID?: string;
    /**
     * Filter that limits results to those that match the specified name.
     */
    name?: string;
    status?: Skyflow.ServiceAccountServiceListServiceAccountsRequestStatus;
    /**
     * Deprecated. ID of the resource. For example, if `resource.type` is `VAULT`, this field is the vault ID. If `resource.type` is `WORKSPACE`, this field is the workspace ID.
     */
    "resource.ID": string;
    /**
     * Deprecated. Type of the resource.
     */
    "resource.type": Skyflow.ServiceAccountServiceListServiceAccountsRequestResourceType;
    /**
     * Deprecated. Name of the resource.
     */
    "resource.name"?: string;
    /**
     * Deprecated. Unique namespace for the resource. Generated by Skyflow.
     */
    "resource.namespace"?: string;
    /**
     * Deprecated. Description of the resource.
     */
    "resource.description"?: string;
    /**
     * Deprecated. Status of the resource.
     */
    "resource.status"?: Skyflow.ServiceAccountServiceListServiceAccountsRequestResourceStatus;
    /**
     * Deprecated. Display name of the resource that appears in user interfaces.
     */
    "resource.displayName"?: string;
    /**
     * Deprecated. Number of levels of contained resources for which to return associated service accounts, starting at the specified resource.
     */
    depth?: string;
}
