/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Skyflow from "../../../index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Pipelines {
    export interface Options {
        environment?: core.Supplier<environments.SkyflowEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Override the X-Skyflow-Account-ID header */
        skyflowAccountId?: core.Supplier<string | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the X-Skyflow-Account-ID header */
        skyflowAccountId?: string | undefined;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Pipelines {
    constructor(protected readonly _options: Pipelines.Options = {}) {}

    /**
     * Gets public encryption keys for the specified account.
     *
     * @param {string} accountId - ID of the account.
     * @param {Pipelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.pipelines.accountServiceListPipelineEncryptionKeys("accountID")
     */
    public accountServiceListPipelineEncryptionKeys(
        accountId: string,
        requestOptions?: Pipelines.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1ListPipelineEncryptionKeysResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__accountServiceListPipelineEncryptionKeys(accountId, requestOptions),
        );
    }

    private async __accountServiceListPipelineEncryptionKeys(
        accountId: string,
        requestOptions?: Pipelines.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1ListPipelineEncryptionKeysResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                `v1/accounts/${encodeURIComponent(accountId)}/pipelines/encryptionKeys`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Skyflow.V1ListPipelineEncryptionKeysResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError(
                    "Timeout exceeded when calling GET /v1/accounts/{accountID}/pipelines/encryptionKeys.",
                );
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Creates a PGP encryption key to use in a pipeline.
     *
     * @param {string} accountId - ID of the account.
     * @param {Skyflow.AccountServiceCreatePipelineEncryptionKeyBody} request
     * @param {Pipelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.pipelines.accountServiceCreatePipelineEncryptionKey("accountID", {
     *         encryptionProtocol: "NONE_PROTOCOL",
     *         pgpKey: {
     *             privateKey: "aliqua",
     *             passphrase: "sunt in sint ut",
     *             publicKey: "e"
     *         }
     *     })
     */
    public accountServiceCreatePipelineEncryptionKey(
        accountId: string,
        request: Skyflow.AccountServiceCreatePipelineEncryptionKeyBody = {},
        requestOptions?: Pipelines.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1CreatePipelineEncryptionKeyResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__accountServiceCreatePipelineEncryptionKey(accountId, request, requestOptions),
        );
    }

    private async __accountServiceCreatePipelineEncryptionKey(
        accountId: string,
        request: Skyflow.AccountServiceCreatePipelineEncryptionKeyBody = {},
        requestOptions?: Pipelines.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1CreatePipelineEncryptionKeyResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                `v1/accounts/${encodeURIComponent(accountId)}/pipelines/encryptionKeys`,
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Skyflow.V1CreatePipelineEncryptionKeyResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError(
                    "Timeout exceeded when calling POST /v1/accounts/{accountID}/pipelines/encryptionKeys.",
                );
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Gets the specified public encryption key.
     *
     * @param {string} accountId - ID of the account.
     * @param {string} id - ID of the key.
     * @param {Pipelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.pipelines.accountServiceGetPipelineEncryptionKey("accountID", "ID")
     */
    public accountServiceGetPipelineEncryptionKey(
        accountId: string,
        id: string,
        requestOptions?: Pipelines.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1GetPipelineEncryptionKeyResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__accountServiceGetPipelineEncryptionKey(accountId, id, requestOptions),
        );
    }

    private async __accountServiceGetPipelineEncryptionKey(
        accountId: string,
        id: string,
        requestOptions?: Pipelines.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1GetPipelineEncryptionKeyResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                `v1/accounts/${encodeURIComponent(accountId)}/pipelines/encryptionKeys/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Skyflow.V1GetPipelineEncryptionKeyResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError(
                    "Timeout exceeded when calling GET /v1/accounts/{accountID}/pipelines/encryptionKeys/{ID}.",
                );
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Deletes the encryption key pair for the specified pipeline.
     *
     * @param {string} accountId - ID of the account.
     * @param {string} id - ID of the key.
     * @param {Pipelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.pipelines.accountServiceDeletePipelineEncryptionKey("accountID", "ID")
     */
    public accountServiceDeletePipelineEncryptionKey(
        accountId: string,
        id: string,
        requestOptions?: Pipelines.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1DeletePipelineEncryptionKeyResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__accountServiceDeletePipelineEncryptionKey(accountId, id, requestOptions),
        );
    }

    private async __accountServiceDeletePipelineEncryptionKey(
        accountId: string,
        id: string,
        requestOptions?: Pipelines.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1DeletePipelineEncryptionKeyResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                `v1/accounts/${encodeURIComponent(accountId)}/pipelines/encryptionKeys/${encodeURIComponent(id)}`,
            ),
            method: "DELETE",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Skyflow.V1DeletePipelineEncryptionKeyResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError(
                    "Timeout exceeded when calling DELETE /v1/accounts/{accountID}/pipelines/encryptionKeys/{ID}.",
                );
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Rotates the encryption key pair for the specified pipeline.
     *
     * @param {string} accountId - ID of the account.
     * @param {string} id - ID of the key.
     * @param {Skyflow.AccountServiceRotatePipelineEncryptionKeyBody} request
     * @param {Pipelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.pipelines.accountServiceRotatePipelineEncryptionKey("accountID", "ID", {
     *         encryptionProtocol: "NONE_PROTOCOL",
     *         pgpKey: {
     *             privateKey: "officia",
     *             passphrase: "qui",
     *             publicKey: "dolore et"
     *         }
     *     })
     */
    public accountServiceRotatePipelineEncryptionKey(
        accountId: string,
        id: string,
        request: Skyflow.AccountServiceRotatePipelineEncryptionKeyBody = {},
        requestOptions?: Pipelines.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1RotatePipelineEncryptionKeyResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__accountServiceRotatePipelineEncryptionKey(accountId, id, request, requestOptions),
        );
    }

    private async __accountServiceRotatePipelineEncryptionKey(
        accountId: string,
        id: string,
        request: Skyflow.AccountServiceRotatePipelineEncryptionKeyBody = {},
        requestOptions?: Pipelines.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1RotatePipelineEncryptionKeyResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                `v1/accounts/${encodeURIComponent(accountId)}/pipelines/encryptionKeys/${encodeURIComponent(id)}/rotate`,
            ),
            method: "PUT",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Skyflow.V1RotatePipelineEncryptionKeyResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError(
                    "Timeout exceeded when calling PUT /v1/accounts/{accountID}/pipelines/encryptionKeys/{ID}/rotate.",
                );
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Lists the pipelines you can access.
     *
     * @param {Skyflow.PipelineServiceListPipelinesRequest} request
     * @param {Pipelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.pipelines.pipelineServiceListPipelines({
     *         vaultID: "vaultID",
     *         "filterOps.name": "filterOps.name",
     *         "filterOps.runTrigger": "TRIGGER_NONE",
     *         "sortOps.sortBy": "sortOps.sortBy",
     *         "sortOps.orderBy": "ASCENDING",
     *         offset: 1000000,
     *         limit: 1000000
     *     })
     */
    public pipelineServiceListPipelines(
        request: Skyflow.PipelineServiceListPipelinesRequest = {},
        requestOptions?: Pipelines.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1ListPipelinesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__pipelineServiceListPipelines(request, requestOptions));
    }

    private async __pipelineServiceListPipelines(
        request: Skyflow.PipelineServiceListPipelinesRequest = {},
        requestOptions?: Pipelines.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1ListPipelinesResponse>> {
        const {
            vaultID: vaultId,
            "filterOps.name": filterOpsName,
            "filterOps.runTrigger": filterOpsRunTrigger,
            "sortOps.sortBy": sortOpsSortBy,
            "sortOps.orderBy": sortOpsOrderBy,
            offset,
            limit,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (vaultId != null) {
            _queryParams["vaultID"] = vaultId;
        }

        if (filterOpsName != null) {
            _queryParams["filterOps.name"] = filterOpsName;
        }

        if (filterOpsRunTrigger != null) {
            _queryParams["filterOps.runTrigger"] = filterOpsRunTrigger;
        }

        if (sortOpsSortBy != null) {
            _queryParams["sortOps.sortBy"] = sortOpsSortBy;
        }

        if (sortOpsOrderBy != null) {
            _queryParams["sortOps.orderBy"] = sortOpsOrderBy;
        }

        if (offset != null) {
            _queryParams["offset"] = offset.toString();
        }

        if (limit != null) {
            _queryParams["limit"] = limit.toString();
        }

        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                "v1/pipelines",
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyflow.V1ListPipelinesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError("Timeout exceeded when calling GET /v1/pipelines.");
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Creates a pipeline.
     *
     * @param {Skyflow.CreatePipelineRequest} request
     * @param {Pipelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.pipelines.pipelineServiceCreatePipeline({
     *         name: "eu adipisicing consectetur eiusmod velit",
     *         displayName: "id commodo",
     *         description: "nulla",
     *         vaultID: "cupidatat incididunt deserunt",
     *         source: {
     *             "dataFormat": "CSV",
     *             "fileNameRegexes": [
     *                 "elit Ut id dolor ea",
     *                 "in amet",
     *                 "dolor elit nulla aliquip adipisicing"
     *             ],
     *             "encryptionProtocol": "NONE_PROTOCOL",
     *             "encryptionKeyID": "sit deserunt est fugiat",
     *             "ftpServer": {
     *                 "transferProtocol": "FTPS",
     *                 "plainText": {
     *                     "hostname": "cupidatat nostrud dolor Du",
     *                     "port": "sint do anim in cillum",
     *                     "username": "id do irure exercitation consequat",
     *                     "password": "ea",
     *                     "sshKeyID": "ad Excepteur"
     *                 },
     *                 "encrypted": {
     *                     "nostrud_4": "dolor ex",
     *                     "encryptedCredentials": "non ad aute fugiat"
     *                 },
     *                 "skyflowHosted": true
     *             },
     *             "s3Bucket": {
     *                 "name": "tempor incididunt in",
     *                 "region": "amet Ut ",
     *                 "assumedRoleARN": "elit dolore"
     *             },
     *             "fileSystem": {
     *                 "inputDirectory": "tempor nisi qui",
     *                 "outputDirectory": "dolor exercitation"
     *             }
     *         },
     *         destination: {
     *             dataFormat: "CSV",
     *             fileNameRegexes: ["sit esse irure sed culp", "ullamc", "tempor dolor"],
     *             encryptionProtocol: "NONE_PROTOCOL",
     *             encryptionKeyID: "incididunt",
     *             ftpServer: {
     *                 transferProtocol: "FTPS",
     *                 plainText: {
     *                     hostname: "ut",
     *                     port: "minim dolor elit laboris",
     *                     username: "sunt commodo incididunt",
     *                     password: "adipisicing cupidatat labore",
     *                     sshKeyID: "in Duis"
     *                 },
     *                 encrypted: {
     *                     encryptedCredentials: "ad sunt occaecat"
     *                 },
     *                 skyflowHosted: false
     *             },
     *             s3Bucket: {
     *                 name: "aliqua enim ullamco nulla in",
     *                 region: "ut ullamco dolore laboris",
     *                 assumedRoleARN: "adi"
     *             },
     *             fileSystem: {
     *                 inputDirectory: "minim labore irure esse",
     *                 outputDirectory: "id commodo quis"
     *             }
     *         },
     *         dataMappings: [{
     *                 tableName: "ipsum enim anim sed ut",
     *                 primaryKey: "officia do dolore",
     *                 fieldMapping: [{
     *                         sourceField: {
     *                             columnName: "incididunt nisi magna",
     *                             jsonFieldName: "voluptate",
     *                             regularExpression: "est dolor nisi in",
     *                             tokenColumnName: "dolore ipsum aute mollit voluptate",
     *                             fixedWidthField: {
     *                                 value: {
     *                                     positionFirst: 98987597,
     *                                     positionLast: -8425045,
     *                                     trimWhitespace: false
     *                                 },
     *                                 matchLines: {
     *                                     positionFirst: 90860125,
     *                                     positionLast: -26762926,
     *                                     regex: "elit"
     *                                 }
     *                             }
     *                         },
     *                         columnName: "veniam ut eu",
     *                         condition: {
     *                             sourceField: {
     *                                 columnName: "est velit eiusmod",
     *                                 jsonFieldName: "esse ut do",
     *                                 regularExpression: "dolore",
     *                                 tokenColumnName: "incididunt occaecat cupidatat labore nostrud",
     *                                 fixedWidthField: {
     *                                     value: {
     *                                         positionFirst: 39971605,
     *                                         positionLast: -95696699,
     *                                         trimWhitespace: true
     *                                     },
     *                                     matchLines: {
     *                                         positionFirst: -90716334,
     *                                         positionLast: -74453305,
     *                                         regex: "reprehenderit"
     *                                     }
     *                                 }
     *                             },
     *                             value: "dolore amet",
     *                             comparator: "NONE_COMPARATOR"
     *                         }
     *                     }, {
     *                         sourceField: {
     *                             columnName: "nisi",
     *                             jsonFieldName: "in sit ipsum",
     *                             regularExpression: "mollit et veniam officia",
     *                             tokenColumnName: "magna proident ad",
     *                             fixedWidthField: {
     *                                 value: {
     *                                     positionFirst: 43144378,
     *                                     positionLast: 47935885,
     *                                     trimWhitespace: false
     *                                 },
     *                                 matchLines: {
     *                                     positionFirst: 57122483,
     *                                     positionLast: 36541906,
     *                                     regex: "incididunt "
     *                                 }
     *                             }
     *                         },
     *                         columnName: "",
     *                         condition: {
     *                             sourceField: {
     *                                 columnName: "Ut sint anim",
     *                                 jsonFieldName: "adipisicing",
     *                                 regularExpression: "sunt",
     *                                 tokenColumnName: "elit non",
     *                                 fixedWidthField: {
     *                                     value: {
     *                                         positionFirst: -92049090,
     *                                         positionLast: 10913852,
     *                                         trimWhitespace: false
     *                                     },
     *                                     matchLines: {
     *                                         positionFirst: -5152405,
     *                                         positionLast: 21968645,
     *                                         regex: "enim Duis"
     *                                     }
     *                                 }
     *                             },
     *                             value: "nostrud est amet dolor proident",
     *                             comparator: "NONE_COMPARATOR"
     *                         }
     *                     }, {
     *                         sourceField: {
     *                             columnName: "mini",
     *                             jsonFieldName: "voluptate",
     *                             regularExpression: "consequat",
     *                             tokenColumnName: "tempor ",
     *                             fixedWidthField: {
     *                                 value: {
     *                                     positionFirst: 83247821,
     *                                     positionLast: -35152964,
     *                                     trimWhitespace: false
     *                                 },
     *                                 matchLines: {
     *                                     positionFirst: 57673593,
     *                                     positionLast: 33226841,
     *                                     regex: "adipisicing nisi Duis Excepteur Ut"
     *                                 }
     *                             }
     *                         },
     *                         columnName: "ullamco",
     *                         condition: {
     *                             sourceField: {
     *                                 columnName: "culpa veniam incididunt",
     *                                 jsonFieldName: "velit Ut",
     *                                 regularExpression: "ea ex nulla",
     *                                 tokenColumnName: "dolore",
     *                                 fixedWidthField: {
     *                                     value: {
     *                                         positionFirst: -79757285,
     *                                         positionLast: -85654917,
     *                                         trimWhitespace: false
     *                                     },
     *                                     matchLines: {
     *                                         positionFirst: -22195160,
     *                                         positionLast: -35982689,
     *                                         regex: "in"
     *                                     }
     *                                 }
     *                             },
     *                             value: "ut",
     *                             comparator: "NONE_COMPARATOR"
     *                         }
     *                     }]
     *             }, {
     *                 tableName: "",
     *                 primaryKey: "consectetur cupidatat eu voluptate ullamco",
     *                 fieldMapping: [{
     *                         sourceField: {
     *                             columnName: "cupidatat et",
     *                             jsonFieldName: "deserunt en",
     *                             regularExpression: "in eiusmod tempor",
     *                             tokenColumnName: "velit",
     *                             fixedWidthField: {
     *                                 value: {
     *                                     positionFirst: 10752238,
     *                                     positionLast: 26992085,
     *                                     trimWhitespace: false
     *                                 },
     *                                 matchLines: {
     *                                     positionFirst: 61678895,
     *                                     positionLast: -56768917,
     *                                     regex: "veniam"
     *                                 }
     *                             }
     *                         },
     *                         columnName: "nisi",
     *                         condition: {
     *                             sourceField: {
     *                                 columnName: "veniam",
     *                                 jsonFieldName: "magna nulla aliquip pariatur",
     *                                 regularExpression: "velit",
     *                                 tokenColumnName: "ullamco in eiusmod qui",
     *                                 fixedWidthField: {
     *                                     value: {
     *                                         positionFirst: 47679416,
     *                                         positionLast: -52170528,
     *                                         trimWhitespace: true
     *                                     },
     *                                     matchLines: {
     *                                         positionFirst: -21344384,
     *                                         positionLast: -73279463,
     *                                         regex: "occaecat pariatur"
     *                                     }
     *                                 }
     *                             },
     *                             value: "Ut incididunt minim",
     *                             comparator: "NONE_COMPARATOR"
     *                         }
     *                     }, {
     *                         sourceField: {
     *                             columnName: "dolor tempor consectetur",
     *                             jsonFieldName: "mollit ut",
     *                             regularExpression: "nulla occaecat sed re",
     *                             tokenColumnName: "et enim",
     *                             fixedWidthField: {
     *                                 value: {
     *                                     positionFirst: 92144522,
     *                                     positionLast: -56350683,
     *                                     trimWhitespace: false
     *                                 },
     *                                 matchLines: {
     *                                     positionFirst: 43826376,
     *                                     positionLast: -16155347,
     *                                     regex: "proident do non"
     *                                 }
     *                             }
     *                         },
     *                         columnName: "am",
     *                         condition: {
     *                             sourceField: {
     *                                 columnName: "quis sit nulla",
     *                                 jsonFieldName: "esse voluptate culpa",
     *                                 regularExpression: "aliqua",
     *                                 tokenColumnName: "adipisicing eu magna sunt in",
     *                                 fixedWidthField: {
     *                                     value: {
     *                                         positionFirst: -61494257,
     *                                         positionLast: 99661735,
     *                                         trimWhitespace: false
     *                                     },
     *                                     matchLines: {
     *                                         positionFirst: -31825741,
     *                                         positionLast: 6766704,
     *                                         regex: "esse culpa"
     *                                     }
     *                                 }
     *                             },
     *                             value: "pariatur",
     *                             comparator: "NONE_COMPARATOR"
     *                         }
     *                     }, {
     *                         sourceField: {
     *                             columnName: "Ut ad reprehenderit",
     *                             jsonFieldName: "in laboris pariatur nostrud",
     *                             regularExpression: "culpa velit sit des",
     *                             tokenColumnName: "ullamco occaecat minim ad aliqui",
     *                             fixedWidthField: {
     *                                 value: {
     *                                     positionFirst: 83166721,
     *                                     positionLast: 3506664,
     *                                     trimWhitespace: false
     *                                 },
     *                                 matchLines: {
     *                                     positionFirst: 55697280,
     *                                     positionLast: 59896642,
     *                                     regex: "Ut fugiat cillum commodo ul"
     *                                 }
     *                             }
     *                         },
     *                         columnName: "consequat qui officia",
     *                         condition: {
     *                             sourceField: {
     *                                 columnName: "in",
     *                                 jsonFieldName: "nostrud minim",
     *                                 regularExpression: "amet",
     *                                 tokenColumnName: "qui tempor quis aliqua",
     *                                 fixedWidthField: {
     *                                     value: {
     *                                         positionFirst: -78009289,
     *                                         positionLast: 45738073,
     *                                         trimWhitespace: false
     *                                     },
     *                                     matchLines: {
     *                                         positionFirst: -37466360,
     *                                         positionLast: 54260523,
     *                                         regex: "Excepteur"
     *                                     }
     *                                 }
     *                             },
     *                             value: "Ut labore eiusmod nostrud",
     *                             comparator: "NONE_COMPARATOR"
     *                         }
     *                     }]
     *             }, {
     *                 tableName: "officia dolore fugia",
     *                 primaryKey: "ipsum cillum ad",
     *                 fieldMapping: [{
     *                         sourceField: {
     *                             columnName: "et dolore incididunt nulla Lorem",
     *                             jsonFieldName: "dolor de",
     *                             regularExpression: "voluptate sint",
     *                             tokenColumnName: "elit fugiat no",
     *                             fixedWidthField: {
     *                                 value: {
     *                                     positionFirst: -67530395,
     *                                     positionLast: 19188687,
     *                                     trimWhitespace: true
     *                                 },
     *                                 matchLines: {
     *                                     positionFirst: -59089711,
     *                                     positionLast: 5519803,
     *                                     regex: "nulla ut consequat tempor minim"
     *                                 }
     *                             }
     *                         },
     *                         columnName: "minim sed",
     *                         condition: {
     *                             sourceField: {
     *                                 columnName: "consequat aliquip sunt sed non",
     *                                 jsonFieldName: "consequat",
     *                                 regularExpression: "in Ut Excepteur est",
     *                                 tokenColumnName: "nisi",
     *                                 fixedWidthField: {
     *                                     value: {
     *                                         positionFirst: 5118720,
     *                                         positionLast: -62591073,
     *                                         trimWhitespace: true
     *                                     },
     *                                     matchLines: {
     *                                         positionFirst: 56612108,
     *                                         positionLast: 27607916,
     *                                         regex: "nulla in in"
     *                                     }
     *                                 }
     *                             },
     *                             value: "c",
     *                             comparator: "NONE_COMPARATOR"
     *                         }
     *                     }, {
     *                         sourceField: {
     *                             columnName: "voluptate ",
     *                             jsonFieldName: "quis",
     *                             regularExpression: "magna laborum do officia",
     *                             tokenColumnName: "amet",
     *                             fixedWidthField: {
     *                                 value: {
     *                                     positionFirst: -29573511,
     *                                     positionLast: 20456212,
     *                                     trimWhitespace: true
     *                                 },
     *                                 matchLines: {
     *                                     positionFirst: 17828093,
     *                                     positionLast: 29612404,
     *                                     regex: "adipisicing ex eiusmod Duis"
     *                                 }
     *                             }
     *                         },
     *                         columnName: "laboris",
     *                         condition: {
     *                             sourceField: {
     *                                 columnName: "ea aliquip eiusmod",
     *                                 jsonFieldName: "magn",
     *                                 regularExpression: "ut",
     *                                 tokenColumnName: "sit commodo Lorem Ut qui",
     *                                 fixedWidthField: {
     *                                     value: {
     *                                         positionFirst: 71357691,
     *                                         positionLast: 84344217,
     *                                         trimWhitespace: false
     *                                     },
     *                                     matchLines: {
     *                                         positionFirst: -53656740,
     *                                         positionLast: -25953433,
     *                                         regex: "adipisicing minim non"
     *                                     }
     *                                 }
     *                             },
     *                             value: "est et reprehenderit mollit",
     *                             comparator: "NONE_COMPARATOR"
     *                         }
     *                     }, {
     *                         sourceField: {
     *                             columnName: "qui laboris dolor",
     *                             jsonFieldName: "ut ex ad irure",
     *                             regularExpression: "occaecat qui ex in nisi",
     *                             tokenColumnName: "cillum magna",
     *                             fixedWidthField: {
     *                                 value: {
     *                                     positionFirst: -52236350,
     *                                     positionLast: 45105528,
     *                                     trimWhitespace: false
     *                                 },
     *                                 matchLines: {
     *                                     positionFirst: 59452180,
     *                                     positionLast: -97750884,
     *                                     regex: "exercitation ea nisi consectetur sit"
     *                                 }
     *                             }
     *                         },
     *                         columnName: "laborum culpa",
     *                         condition: {
     *                             sourceField: {
     *                                 columnName: "consectetur fugiat in",
     *                                 jsonFieldName: "aliquip",
     *                                 regularExpression: "laboris culpa voluptate ut occaecat",
     *                                 tokenColumnName: "elit proident ullamco nisi",
     *                                 fixedWidthField: {
     *                                     value: {
     *                                         positionFirst: 60903317,
     *                                         positionLast: -48444023,
     *                                         trimWhitespace: false
     *                                     },
     *                                     matchLines: {
     *                                         positionFirst: 45477935,
     *                                         positionLast: 50124003,
     *                                         regex: "aute Ut do aliquip"
     *                                     }
     *                                 }
     *                             },
     *                             value: "irure nostrud ad",
     *                             comparator: "NONE_COMPARATOR"
     *                         }
     *                     }]
     *             }],
     *         action: "NONE_PROTOCOL",
     *         runTriggers: ["TRIGGER_NONE", "TRIGGER_NONE", "TRIGGER_NONE"],
     *         primaryKey: "mollit voluptate Duis reprehenderit ullamco",
     *         reportOptions: {
     *             recordIdentifiers: ["ullamco ut mollit", "irure ullamco dolore", "nulla ad id"]
     *         }
     *     })
     */
    public pipelineServiceCreatePipeline(
        request: Skyflow.CreatePipelineRequest = {},
        requestOptions?: Pipelines.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1CreatePipelineResponse> {
        return core.HttpResponsePromise.fromPromise(this.__pipelineServiceCreatePipeline(request, requestOptions));
    }

    private async __pipelineServiceCreatePipeline(
        request: Skyflow.CreatePipelineRequest = {},
        requestOptions?: Pipelines.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1CreatePipelineResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                "v1/pipelines",
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyflow.V1CreatePipelineResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError("Timeout exceeded when calling POST /v1/pipelines.");
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns the specified pipeline.
     *
     * @param {string} id - ID of the pipeline.
     * @param {Pipelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.pipelines.pipelineServiceGetPipeline("ID")
     */
    public pipelineServiceGetPipeline(
        id: string,
        requestOptions?: Pipelines.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1GetPipelineResponse> {
        return core.HttpResponsePromise.fromPromise(this.__pipelineServiceGetPipeline(id, requestOptions));
    }

    private async __pipelineServiceGetPipeline(
        id: string,
        requestOptions?: Pipelines.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1GetPipelineResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                `v1/pipelines/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyflow.V1GetPipelineResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError("Timeout exceeded when calling GET /v1/pipelines/{ID}.");
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Deletes the specified pipeline and the entities it contains.
     *
     * @param {string} id - ID of the pipeline.
     * @param {Pipelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.pipelines.pipelineServiceDeletePipeline("ID")
     */
    public pipelineServiceDeletePipeline(
        id: string,
        requestOptions?: Pipelines.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1DeletePipelineResponse> {
        return core.HttpResponsePromise.fromPromise(this.__pipelineServiceDeletePipeline(id, requestOptions));
    }

    private async __pipelineServiceDeletePipeline(
        id: string,
        requestOptions?: Pipelines.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1DeletePipelineResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                `v1/pipelines/${encodeURIComponent(id)}`,
            ),
            method: "DELETE",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyflow.V1DeletePipelineResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError("Timeout exceeded when calling DELETE /v1/pipelines/{ID}.");
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Runs the specified pipeline.
     *
     * @param {string} id - ID of the pipeline.
     * @param {Skyflow.V1PipelineServiceRunPipelineBody} request
     * @param {Pipelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.pipelines.pipelineServiceRunPipeline("ID", {
     *         fileNameRegexes: ["et exercitation velit", "mollit proident", "dolore"],
     *         exportDirectory: "ullamco incididunt irure culpa velit"
     *     })
     */
    public pipelineServiceRunPipeline(
        id: string,
        request: Skyflow.V1PipelineServiceRunPipelineBody = {},
        requestOptions?: Pipelines.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1RunPipelineResponse> {
        return core.HttpResponsePromise.fromPromise(this.__pipelineServiceRunPipeline(id, request, requestOptions));
    }

    private async __pipelineServiceRunPipeline(
        id: string,
        request: Skyflow.V1PipelineServiceRunPipelineBody = {},
        requestOptions?: Pipelines.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1RunPipelineResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                `v1/pipelines/${encodeURIComponent(id)}/run`,
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyflow.V1RunPipelineResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError("Timeout exceeded when calling POST /v1/pipelines/{ID}/run.");
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Stops the specified pipeline run.
     *
     * @param {string} id - ID of the pipeline.
     * @param {string} runId - ID of the pipeline run.
     * @param {Skyflow.V1PipelineServiceStopPipelineRunBody} request
     * @param {Pipelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.pipelines.pipelineServiceStopPipelineRun("ID", "runID", {
     *         "nisic12": "occaecat consectetur",
     *         "voluptate_ab_": 28200642.516746923
     *     })
     */
    public pipelineServiceStopPipelineRun(
        id: string,
        runId: string,
        request: Skyflow.V1PipelineServiceStopPipelineRunBody,
        requestOptions?: Pipelines.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1StopPipelineRunResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__pipelineServiceStopPipelineRun(id, runId, request, requestOptions),
        );
    }

    private async __pipelineServiceStopPipelineRun(
        id: string,
        runId: string,
        request: Skyflow.V1PipelineServiceStopPipelineRunBody,
        requestOptions?: Pipelines.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1StopPipelineRunResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                `v1/pipelines/${encodeURIComponent(id)}/runs/${encodeURIComponent(runId)}/stop`,
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyflow.V1StopPipelineRunResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError(
                    "Timeout exceeded when calling POST /v1/pipelines/{ID}/runs/{runID}/stop.",
                );
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Lists runs of the specified pipeline.
     *
     * @param {string} pipelineId - ID of the pipeline.
     * @param {Skyflow.PipelineServiceListPipelineRunsRequest} request
     * @param {Pipelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.pipelines.pipelineServiceListPipelineRuns("pipelineID", {
     *         "filterOps.state": "NONE_STATE",
     *         offset: 1000000,
     *         limit: 1000000
     *     })
     */
    public pipelineServiceListPipelineRuns(
        pipelineId: string,
        request: Skyflow.PipelineServiceListPipelineRunsRequest = {},
        requestOptions?: Pipelines.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1ListPipelineRunsResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__pipelineServiceListPipelineRuns(pipelineId, request, requestOptions),
        );
    }

    private async __pipelineServiceListPipelineRuns(
        pipelineId: string,
        request: Skyflow.PipelineServiceListPipelineRunsRequest = {},
        requestOptions?: Pipelines.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1ListPipelineRunsResponse>> {
        const { "filterOps.state": filterOpsState, offset, limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (filterOpsState != null) {
            _queryParams["filterOps.state"] = filterOpsState;
        }

        if (offset != null) {
            _queryParams["offset"] = offset.toString();
        }

        if (limit != null) {
            _queryParams["limit"] = limit.toString();
        }

        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                `v1/pipelines/${encodeURIComponent(pipelineId)}/runs`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyflow.V1ListPipelineRunsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError(
                    "Timeout exceeded when calling GET /v1/pipelines/{pipelineID}/runs.",
                );
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns the specified pipeline run.
     *
     * @param {string} pipelineId - ID of the pipeline.
     * @param {string} id - ID of the pipeline run.
     * @param {Pipelines.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.pipelines.pipelineServiceGetPipelineRun("pipelineID", "ID")
     */
    public pipelineServiceGetPipelineRun(
        pipelineId: string,
        id: string,
        requestOptions?: Pipelines.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1GetPipelineRunResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__pipelineServiceGetPipelineRun(pipelineId, id, requestOptions),
        );
    }

    private async __pipelineServiceGetPipelineRun(
        pipelineId: string,
        id: string,
        requestOptions?: Pipelines.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1GetPipelineRunResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                `v1/pipelines/${encodeURIComponent(pipelineId)}/runs/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyflow.V1GetPipelineRunResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError(
                    "Timeout exceeded when calling GET /v1/pipelines/{pipelineID}/runs/{ID}.",
                );
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
