/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         vault_id: "VAULT_ID",
 *         text: "I love to play cricket.",
 *         check_toxicity: true,
 *         deny_topics: ["sports"]
 *     }
 */
export interface CheckGuardrailsRequest {
    vault_id: Skyflow.VaultId;
    /** Text to check against guardrails. */
    text: string;
    /** Check for toxicity in the text. */
    check_toxicity?: boolean;
    /** List of topics to deny. */
    deny_topics?: string[];
}
