/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {}
 */
export interface RecordServiceGetRecordRequest {
    /**
     * Redaction level to enforce for the returned record. Subject to policies assigned to the API caller.
     */
    redaction?: Skyflow.RecordServiceGetRecordRequestRedaction;
    /**
     * If `true`, this operation returns tokens for fields with tokenization enabled. Only applicable if `skyflow_id` values are specified.
     */
    tokenization?: boolean;
    /**
     * Fields to return for the record, with one value per `fields` URL parameter. For example, `?fields=abc&fields=123`.<br /><br />If not specified, returns all fields.
     */
    fields?: string | string[];
    /**
     * If `true`, returns download URLs for fields with a file data type. URLs are valid for 15 minutes. If virus scanning is enabled, only returns if the file is clean.
     */
    downloadURL?: boolean;
}
