/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         records: [{
 *                 fields: {
 *                     "drivers_license_number": "13456789",
 *                     "name": "John",
 *                     "phone_number": "1236784563",
 *                     "ssn": "123-45-6789"
 *                 }
 *             }, {
 *                 fields: {
 *                     "drivers_license_number": "98765432",
 *                     "name": "James",
 *                     "phone_number": "9876543215",
 *                     "ssn": "345-45-9876"
 *                 }
 *             }],
 *         tokenization: true,
 *         upsert: "drivers_license_number",
 *         homogeneous: false
 *     }
 */
export interface RecordServiceInsertRecordBody {
    /** Record values and tokens. */
    records?: Skyflow.V1FieldRecords[];
    /** If `true`, this operation returns tokens for fields with tokenization enabled. */
    tokenization?: boolean;
    /** Name of a unique column in the table. Uses upsert operations to check if a record exists based on the unique column's value. If a matching record exists, the record updates with the values you provide. If a matching record doesn't exist, the upsert operation inserts a new record.<br /><br />When you upsert a field, include the entire contents you want the field to store. For JSON fields, include all nested fields and values. If a nested field isn't included, it's removed. */
    upsert?: string;
    /** If `true`, this operation mandates that all the records have the same fields. This parameter does not work with upsert. */
    homogeneous?: boolean;
    byot?: Skyflow.V1Byot;
}
