/*
 * Skyflow Data
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {ApiNotebookData} from './ApiNotebookData';

/**
 * The ApiCreateNotebookDataRequest model module.
 * @module model/ApiCreateNotebookDataRequest
 * @version 1.0
 */
export class ApiCreateNotebookDataRequest {
  /**
   * Constructs a new <code>ApiCreateNotebookDataRequest</code>.
   * @alias module:model/ApiCreateNotebookDataRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ApiCreateNotebookDataRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiCreateNotebookDataRequest} obj Optional instance to populate.
   * @return {module:model/ApiCreateNotebookDataRequest} The populated <code>ApiCreateNotebookDataRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ApiCreateNotebookDataRequest();
      if (data.hasOwnProperty('orgID'))
        obj.orgID = ApiClient.convertToType(data['orgID'], 'String');
      if (data.hasOwnProperty('vaultID'))
        obj.vaultID = ApiClient.convertToType(data['vaultID'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = ApiNotebookData.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {String} orgID
 */
ApiCreateNotebookDataRequest.prototype.orgID = undefined;

/**
 * @member {String} vaultID
 */
ApiCreateNotebookDataRequest.prototype.vaultID = undefined;

/**
 * @member {module:model/ApiNotebookData} data
 */
ApiCreateNotebookDataRequest.prototype.data = undefined;


