/*
 * Skyflow Data
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {RpcStatus} from './RpcStatus';

/**
 * The ApiDeleteUserResponse model module.
 * @module model/ApiDeleteUserResponse
 * @version 1.0
 */
export class ApiDeleteUserResponse {
  /**
   * Constructs a new <code>ApiDeleteUserResponse</code>.
   * @alias module:model/ApiDeleteUserResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ApiDeleteUserResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiDeleteUserResponse} obj Optional instance to populate.
   * @return {module:model/ApiDeleteUserResponse} The populated <code>ApiDeleteUserResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ApiDeleteUserResponse();
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = RpcStatus.constructFromObject(data['status']);
    }
    return obj;
  }
}

/**
 * @member {String} ID
 */
ApiDeleteUserResponse.prototype.ID = undefined;

/**
 * @member {module:model/RpcStatus} status
 */
ApiDeleteUserResponse.prototype.status = undefined;


