/*
 * Skyflow Data
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The ApiDeleteOrganizationResponse model module.
 * @module model/ApiDeleteOrganizationResponse
 * @version 1.0
 */
export class ApiDeleteOrganizationResponse {
  /**
   * Constructs a new <code>ApiDeleteOrganizationResponse</code>.
   * @alias module:model/ApiDeleteOrganizationResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ApiDeleteOrganizationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiDeleteOrganizationResponse} obj Optional instance to populate.
   * @return {module:model/ApiDeleteOrganizationResponse} The populated <code>ApiDeleteOrganizationResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ApiDeleteOrganizationResponse();
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} ID
 */
ApiDeleteOrganizationResponse.prototype.ID = undefined;


