/*
 * Skyflow Data
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * The ApiDeleteNotebookTableResponse model module.
 * @module model/ApiDeleteNotebookTableResponse
 * @version 1.0
 */
export class ApiDeleteNotebookTableResponse {
  /**
   * Constructs a new <code>ApiDeleteNotebookTableResponse</code>.
   * @alias module:model/ApiDeleteNotebookTableResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ApiDeleteNotebookTableResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiDeleteNotebookTableResponse} obj Optional instance to populate.
   * @return {module:model/ApiDeleteNotebookTableResponse} The populated <code>ApiDeleteNotebookTableResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ApiDeleteNotebookTableResponse();
    }
    return obj;
  }
}

