/*
 * Skyflow Data
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {ApiFieldData} from './ApiFieldData';

/**
 * The ApiGetNotebookDataResponse model module.
 * @module model/ApiGetNotebookDataResponse
 * @version 1.0
 */
export class ApiGetNotebookDataResponse {
  /**
   * Constructs a new <code>ApiGetNotebookDataResponse</code>.
   * @alias module:model/ApiGetNotebookDataResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ApiGetNotebookDataResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiGetNotebookDataResponse} obj Optional instance to populate.
   * @return {module:model/ApiGetNotebookDataResponse} The populated <code>ApiGetNotebookDataResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ApiGetNotebookDataResponse();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], [ApiFieldData]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/ApiFieldData>} data
 */
ApiGetNotebookDataResponse.prototype.data = undefined;


