/*
 * Skyflow Data
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * Enum class ApiNotebookOperation.
 * @enum {String}
 * @readonly
 */
const ApiNotebookOperation = {
  /**
   * value: "EXACT_MATCH"
   * @const
   */
  EXACT_MATCH: "EXACT_MATCH",

  /**
   * value: "RANGE"
   * @const
   */
  RANGE: "RANGE",

  /**
   * value: "AGGREGATE"
   * @const
   */
  AGGREGATE: "AGGREGATE",

  /**
   * value: "UNENCRYPTED"
   * @const
   */
  UNENCRYPTED: "UNENCRYPTED",

  /**
   * Returns a <code>ApiNotebookOperation</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/ApiNotebookOperation} The enum <code>ApiNotebookOperation</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {ApiNotebookOperation};
