/*
 * Skyflow Data
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {ApiFieldData} from './ApiFieldData';

/**
 * The ApiRowData model module.
 * @module model/ApiRowData
 * @version 1.0
 */
export class ApiRowData {
  /**
   * Constructs a new <code>ApiRowData</code>.
   * @alias module:model/ApiRowData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ApiRowData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiRowData} obj Optional instance to populate.
   * @return {module:model/ApiRowData} The populated <code>ApiRowData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ApiRowData();
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], [ApiFieldData]);
    }
    return obj;
  }
}

/**
 * @member {String} ID
 */
ApiRowData.prototype.ID = undefined;

/**
 * @member {Array.<module:model/ApiFieldData>} value
 */
ApiRowData.prototype.value = undefined;


