/*
 * Skyflow Data
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';

/**
 * Enum class ApiUserStatus.
 * @enum {String}
 * @readonly
 */
const ApiUserStatus = {
  /**
   * value: "UNUSED"
   * @const
   */
  UNUSED: "UNUSED",

  /**
   * value: "ACTIVE"
   * @const
   */
  ACTIVE: "ACTIVE",

  /**
   * value: "INACTIVE"
   * @const
   */
  INACTIVE: "INACTIVE",

  /**
   * Returns a <code>ApiUserStatus</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/ApiUserStatus} The enum <code>ApiUserStatus</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {ApiUserStatus};
