/*
 * Skyflow Data
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {ApiUser} from './ApiUser';

/**
 * The ApiUpdateUserRequest model module.
 * @module model/ApiUpdateUserRequest
 * @version 1.0
 */
export class ApiUpdateUserRequest {
  /**
   * Constructs a new <code>ApiUpdateUserRequest</code>.
   * @alias module:model/ApiUpdateUserRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ApiUpdateUserRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiUpdateUserRequest} obj Optional instance to populate.
   * @return {module:model/ApiUpdateUserRequest} The populated <code>ApiUpdateUserRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ApiUpdateUserRequest();
      if (data.hasOwnProperty('User'))
        obj.user = ApiUser.constructFromObject(data['User']);
      if (data.hasOwnProperty('orgID'))
        obj.orgID = ApiClient.convertToType(data['orgID'], 'String');
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/ApiUser} user
 */
ApiUpdateUserRequest.prototype.user = undefined;

/**
 * @member {String} orgID
 */
ApiUpdateUserRequest.prototype.orgID = undefined;

/**
 * @member {String} ID
 */
ApiUpdateUserRequest.prototype.ID = undefined;


