/*
 * Skyflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {ProtobufAny} from './ProtobufAny';

/**
 * The RuntimeStreamError model module.
 * @module model/RuntimeStreamError
 * @version v1
 */
export class RuntimeStreamError {
  /**
   * Constructs a new <code>RuntimeStreamError</code>.
   * @alias module:model/RuntimeStreamError
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RuntimeStreamError</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RuntimeStreamError} obj Optional instance to populate.
   * @return {module:model/RuntimeStreamError} The populated <code>RuntimeStreamError</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RuntimeStreamError();
      if (data.hasOwnProperty('grpc_code'))
        obj.grpcCode = ApiClient.convertToType(data['grpc_code'], 'Number');
      if (data.hasOwnProperty('http_code'))
        obj.httpCode = ApiClient.convertToType(data['http_code'], 'Number');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('http_status'))
        obj.httpStatus = ApiClient.convertToType(data['http_status'], 'String');
      if (data.hasOwnProperty('details'))
        obj.details = ApiClient.convertToType(data['details'], [ProtobufAny]);
    }
    return obj;
  }
}

/**
 * @member {Number} grpcCode
 */
RuntimeStreamError.prototype.grpcCode = undefined;

/**
 * @member {Number} httpCode
 */
RuntimeStreamError.prototype.httpCode = undefined;

/**
 * @member {String} message
 */
RuntimeStreamError.prototype.message = undefined;

/**
 * @member {String} httpStatus
 */
RuntimeStreamError.prototype.httpStatus = undefined;

/**
 * @member {Array.<module:model/ProtobufAny>} details
 */
RuntimeStreamError.prototype.details = undefined;


