/*
 * Skyflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import BaseEntity from './BaseEntity';

/**
 * Enum class TokenAccessControlAccessControl.
 * @enum {String}
 * @readonly
 */
const TokenAccessControlAccessControl = {
  /**
   * value: "NONE"
   * @const
   */
  NONE: "NONE",

  /**
   * value: "TTL_7_DAYS"
   * @const
   */
  tTL7DAYS: "TTL_7_DAYS",

  /**
   * value: "ADMIN"
   * @const
   */
  ADMIN: "ADMIN",

  /**
   * Returns a <code>TokenAccessControlAccessControl</code> enum value from a JavaScript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/TokenAccessControlAccessControl} The enum <code>TokenAccessControlAccessControl</code> value.
   */
  constructFromObject: function(object) {
    return object;
  }
};

export {TokenAccessControlAccessControl};
