/*
 * Skyflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {V1FieldData} from './V1FieldData';
import BaseEntity from './BaseEntity';

/**
 * The V1BulkRecords model module.
 * @module model/V1BulkRecords
 * @version v1
 */
export class V1BulkRecords  {
  /**
   * Constructs a new <code>V1BulkRecords</code>.
   * @alias module:model/V1BulkRecords
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1BulkRecords</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1BulkRecords} obj Optional instance to populate.
   * @return {module:model/V1BulkRecords} The populated <code>V1BulkRecords</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1BulkRecords();
      if (data.hasOwnProperty('fields'))
        obj.fields = ApiClient.convertToType(data['fields'], [V1FieldData]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/V1FieldData>} fields
 */
V1BulkRecords.prototype.fields = undefined;


