/*
 * Skyflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {V1Application} from './V1Application';

/**
 * The V1CreateApplicationRequest model module.
 * @module model/V1CreateApplicationRequest
 * @version v1
 */
export class V1CreateApplicationRequest {
  /**
   * Constructs a new <code>V1CreateApplicationRequest</code>.
   * @alias module:model/V1CreateApplicationRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1CreateApplicationRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1CreateApplicationRequest} obj Optional instance to populate.
   * @return {module:model/V1CreateApplicationRequest} The populated <code>V1CreateApplicationRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1CreateApplicationRequest();
      if (data.hasOwnProperty('apiKey'))
        obj.apiKey = V1Application.constructFromObject(data['apiKey']);
      if (data.hasOwnProperty('orgID'))
        obj.orgID = ApiClient.convertToType(data['orgID'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/V1Application} apiKey
 */
V1CreateApplicationRequest.prototype.apiKey = undefined;

/**
 * @member {String} orgID
 */
V1CreateApplicationRequest.prototype.orgID = undefined;


