/*
 * Skyflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {V1User} from './V1User';
import BaseEntity from './BaseEntity';

/**
 * The V1CreateUserRequest model module.
 * @module model/V1CreateUserRequest
 * @version v1
 */
export class V1CreateUserRequest  {
  /**
   * Constructs a new <code>V1CreateUserRequest</code>.
   * @alias module:model/V1CreateUserRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1CreateUserRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1CreateUserRequest} obj Optional instance to populate.
   * @return {module:model/V1CreateUserRequest} The populated <code>V1CreateUserRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1CreateUserRequest();
      if (data.hasOwnProperty('user'))
        obj.user = V1User.constructFromObject(data['user']);
      if (data.hasOwnProperty('orgID'))
        obj.orgID = ApiClient.convertToType(data['orgID'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/V1User} user
 */
V1CreateUserRequest.prototype.user = undefined;

/**
 * @member {String} orgID
 */
V1CreateUserRequest.prototype.orgID = undefined;


