/*
 * Skyflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {V1Policy} from './V1Policy';
import BaseEntity from './BaseEntity';

/**
 * The V1CreatePolicyRequest model module.
 * @module model/V1CreatePolicyRequest
 * @version v1
 */
export class V1CreatePolicyRequest  {
  /**
   * Constructs a new <code>V1CreatePolicyRequest</code>.
   * @alias module:model/V1CreatePolicyRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1CreatePolicyRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1CreatePolicyRequest} obj Optional instance to populate.
   * @return {module:model/V1CreatePolicyRequest} The populated <code>V1CreatePolicyRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1CreatePolicyRequest();
      if (data.hasOwnProperty('policy'))
        obj.policy = V1Policy.constructFromObject(data['policy']);
    }
    return obj;
  }
}

/**
 * @member {module:model/V1Policy} policy
 */
V1CreatePolicyRequest.prototype.policy = undefined;


