/*
 * Skyflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import BaseEntity from './BaseEntity';

/**
 * The V1FieldData model module.
 * @module model/V1FieldData
 * @version v1
 */
export class V1FieldData  {
  /**
   * Constructs a new <code>V1FieldData</code>.
   * @alias module:model/V1FieldData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1FieldData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1FieldData} obj Optional instance to populate.
   * @return {module:model/V1FieldData} The populated <code>V1FieldData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1FieldData();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * Name of the Field
 * @member {String} name
 */
V1FieldData.prototype.name = undefined;

/**
 * Value of the Field
 * @member {String} value
 */
V1FieldData.prototype.value = undefined;


