/*
 * Skyflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {V1FieldType} from './V1FieldType';

/**
 * The V1FieldTypeData model module.
 * @module model/V1FieldTypeData
 * @version v1
 */
export class V1FieldTypeData {
  /**
   * Constructs a new <code>V1FieldTypeData</code>.
   * @alias module:model/V1FieldTypeData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1FieldTypeData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1FieldTypeData} obj Optional instance to populate.
   * @return {module:model/V1FieldTypeData} The populated <code>V1FieldTypeData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1FieldTypeData();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = V1FieldType.constructFromObject(data['type']);
    }
    return obj;
  }
}

/**
 * Name of the Field
 * @member {String} name
 */
V1FieldTypeData.prototype.name = undefined;

/**
 * Value of the Field
 * @member {String} value
 */
V1FieldTypeData.prototype.value = undefined;

/**
 * Data Type of the Field
 * @member {module:model/V1FieldType} type
 */
V1FieldTypeData.prototype.type = undefined;


