/*
 * Skyflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import BaseEntity from './BaseEntity';

/**
 * The V1GenerateTokensRequest model module.
 * @module model/V1GenerateTokensRequest
 * @version v1
 */
export class V1GenerateTokensRequest  {
  /**
   * Constructs a new <code>V1GenerateTokensRequest</code>.
   * @alias module:model/V1GenerateTokensRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1GenerateTokensRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1GenerateTokensRequest} obj Optional instance to populate.
   * @return {module:model/V1GenerateTokensRequest} The populated <code>V1GenerateTokensRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1GenerateTokensRequest();
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * The EMail Address of Skyflow User
 * @member {String} username
 */
V1GenerateTokensRequest.prototype.username = undefined;

/**
 * Password for this User
 * @member {String} password
 */
V1GenerateTokensRequest.prototype.password = undefined;


