/*
 * Skyflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {V1Organization} from './V1Organization';

/**
 * The V1GetOrganizationResponse model module.
 * @module model/V1GetOrganizationResponse
 * @version v1
 */
export class V1GetOrganizationResponse {
  /**
   * Constructs a new <code>V1GetOrganizationResponse</code>.
   * @alias module:model/V1GetOrganizationResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1GetOrganizationResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1GetOrganizationResponse} obj Optional instance to populate.
   * @return {module:model/V1GetOrganizationResponse} The populated <code>V1GetOrganizationResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1GetOrganizationResponse();
      if (data.hasOwnProperty('organization'))
        obj.organization = V1Organization.constructFromObject(data['organization']);
    }
    return obj;
  }
}

/**
 * @member {module:model/V1Organization} organization
 */
V1GetOrganizationResponse.prototype.organization = undefined;


