/*
 * Skyflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */


/**
 * The V1GetVaultInterfacesModelsResponse model module.
 * @module model/V1GetVaultInterfacesModelsResponse
 * @version v1
 */
export class V1GetVaultInterfacesModelsResponse {
  /**
   * Constructs a new <code>V1GetVaultInterfacesModelsResponse</code>.
   * @alias module:model/V1GetVaultInterfacesModelsResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1GetVaultInterfacesModelsResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1GetVaultInterfacesModelsResponse} obj Optional instance to populate.
   * @return {module:model/V1GetVaultInterfacesModelsResponse} The populated <code>V1GetVaultInterfacesModelsResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1GetVaultInterfacesModelsResponse();
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('iconURL'))
        obj.iconURL = ApiClient.convertToType(data['iconURL'], 'String');
      if (data.hasOwnProperty('learnMoreURL'))
        obj.learnMoreURL = ApiClient.convertToType(data['learnMoreURL'], 'String');
      if (data.hasOwnProperty('available'))
        obj.available = ApiClient.convertToType(data['available'], 'Boolean');
    }
    return obj;
  }
}

/**
 * This should be mapped to Interfaces[] during Create Vault Call
 * @member {String} ID
 */
V1GetVaultInterfacesModelsResponse.prototype.ID = undefined;

/**
 * @member {String} name
 */
V1GetVaultInterfacesModelsResponse.prototype.name = undefined;

/**
 * @member {String} description
 */
V1GetVaultInterfacesModelsResponse.prototype.description = undefined;

/**
 * @member {String} iconURL
 */
V1GetVaultInterfacesModelsResponse.prototype.iconURL = undefined;

/**
 * @member {String} learnMoreURL
 */
V1GetVaultInterfacesModelsResponse.prototype.learnMoreURL = undefined;

/**
 * @member {Boolean} available
 */
V1GetVaultInterfacesModelsResponse.prototype.available = undefined;


