/*
 * Skyflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {V1Address} from './V1Address';
import BaseEntity from './BaseEntity';

/**
 * The V1Organization model module.
 * @module model/V1Organization
 * @version v1
 */
export class V1Organization  {
  /**
   * Constructs a new <code>V1Organization</code>.
   * @alias module:model/V1Organization
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1Organization</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1Organization} obj Optional instance to populate.
   * @return {module:model/V1Organization} The populated <code>V1Organization</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1Organization();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('displayName'))
        obj.displayName = ApiClient.convertToType(data['displayName'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('contactAddress'))
        obj.contactAddress = V1Address.constructFromObject(data['contactAddress']);
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'String');
    }
    return obj;
  }
}

/**
 * Name of the Organization with AlphaNumeric Characters to uniquely identify an Org
 * @member {String} name
 */
V1Organization.prototype.name = undefined;

/**
 * Display Name for the Organization which can be used for UI Rendering
 * @member {String} displayName
 */
V1Organization.prototype.displayName = undefined;

/**
 * Description for the Organization
 * @member {String} description
 */
V1Organization.prototype.description = undefined;

/**
 * Contact Address for the Organization
 * @member {module:model/V1Address} contactAddress
 */
V1Organization.prototype.contactAddress = undefined;

/**
 * This will be generated by Server and cannot be user generated
 * @member {String} ID
 */
V1Organization.prototype.ID = undefined;


