/*
 * Skyflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {V1ResourceType} from './V1ResourceType';
import BaseEntity from './BaseEntity';

/**
 * The V1Resource model module.
 * @module model/V1Resource
 * @version v1
 */
export class V1Resource  {
  /**
   * Constructs a new <code>V1Resource</code>.
   * @alias module:model/V1Resource
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1Resource</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1Resource} obj Optional instance to populate.
   * @return {module:model/V1Resource} The populated <code>V1Resource</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1Resource();
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = V1ResourceType.constructFromObject(data['type']);
    }
    return obj;
  }
}

/**
 * Resource to which policies are being defined 
 * @member {String} ID
 */
V1Resource.prototype.ID = undefined;

/**
 * Type of a Resource being Defined
 * @member {module:model/V1ResourceType} type
 */
V1Resource.prototype.type = undefined;


