/*
 * Skyflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {V1TokenAccessControl} from './V1TokenAccessControl';

/**
 * The V1TokenPolicy model module.
 * @module model/V1TokenPolicy
 * @version v1
 */
export class V1TokenPolicy {
  /**
   * Constructs a new <code>V1TokenPolicy</code>.
   * @alias module:model/V1TokenPolicy
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1TokenPolicy</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1TokenPolicy} obj Optional instance to populate.
   * @return {module:model/V1TokenPolicy} The populated <code>V1TokenPolicy</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1TokenPolicy();
      if (data.hasOwnProperty('object'))
        obj._object = ApiClient.convertToType(data['object'], {'String': V1TokenAccessControl});
    }
    return obj;
  }
}

/**
 * @member {Object.<String, module:model/V1TokenAccessControl>} _object
 */
V1TokenPolicy.prototype._object = undefined;


