/*
 * Skyflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {TokenAccessControlAccessControl} from './TokenAccessControlAccessControl';
import BaseEntity from './BaseEntity';

/**
 * The V1TokenAccessControl model module.
 * @module model/V1TokenAccessControl
 * @version v1
 */
export class V1TokenAccessControl  {
  /**
   * Constructs a new <code>V1TokenAccessControl</code>.
   * @alias module:model/V1TokenAccessControl
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1TokenAccessControl</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1TokenAccessControl} obj Optional instance to populate.
   * @return {module:model/V1TokenAccessControl} The populated <code>V1TokenAccessControl</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1TokenAccessControl();
      if (data.hasOwnProperty('accessControls'))
        obj.accessControls = ApiClient.convertToType(data['accessControls'], [TokenAccessControlAccessControl]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/TokenAccessControlAccessControl>} accessControls
 */
V1TokenAccessControl.prototype.accessControls = undefined;


