/*
 * Skyflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.14-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

import {PolicyPermissions} from './PolicyPermissions';
import BaseEntity from './BaseEntity';

/**
 * The V1UpdatePolicyRequest model module.
 * @module model/V1UpdatePolicyRequest
 * @version v1
 */
export class V1UpdatePolicyRequest  {
  /**
   * Constructs a new <code>V1UpdatePolicyRequest</code>.
   * @alias module:model/V1UpdatePolicyRequest
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>V1UpdatePolicyRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/V1UpdatePolicyRequest} obj Optional instance to populate.
   * @return {module:model/V1UpdatePolicyRequest} The populated <code>V1UpdatePolicyRequest</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new V1UpdatePolicyRequest();
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'String');
      if (data.hasOwnProperty('permissions'))
        obj.permissions = ApiClient.convertToType(data['permissions'], [PolicyPermissions]);
    }
    return obj;
  }
}

/**
 * @member {String} ID
 */
V1UpdatePolicyRequest.prototype.ID = undefined;

/**
 * List of applicable permissions to Replace with for given resource
 * @member {Array.<module:model/PolicyPermissions>} permissions
 */
V1UpdatePolicyRequest.prototype.permissions = undefined;


