/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Audit } from "./api/resources/audit/client/Client";
import { BinLookup } from "./api/resources/binLookup/client/Client";
import { Records } from "./api/resources/records/client/Client";
import { Tokens } from "./api/resources/tokens/client/Client";
import { Query } from "./api/resources/query/client/Client";
import { Authentication } from "./api/resources/authentication/client/Client";
import { Guardrails } from "./api/resources/guardrails/client/Client";
import { Strings } from "./api/resources/strings/client/Client";
import { Files } from "./api/resources/files/client/Client";

export declare namespace SkyflowClient {
    export interface Options {
        environment?: core.Supplier<environments.SkyflowEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class SkyflowClient {
    protected _audit: Audit | undefined;
    protected _binLookup: BinLookup | undefined;
    protected _records: Records | undefined;
    protected _tokens: Tokens | undefined;
    protected _query: Query | undefined;
    protected _authentication: Authentication | undefined;
    protected _guardrails: Guardrails | undefined;
    protected _strings: Strings | undefined;
    protected _files: Files | undefined;

    constructor(protected readonly _options: SkyflowClient.Options) {}

    public get audit(): Audit {
        return (this._audit ??= new Audit(this._options));
    }

    public get binLookup(): BinLookup {
        return (this._binLookup ??= new BinLookup(this._options));
    }

    public get records(): Records {
        return (this._records ??= new Records(this._options));
    }

    public get tokens(): Tokens {
        return (this._tokens ??= new Tokens(this._options));
    }

    public get query(): Query {
        return (this._query ??= new Query(this._options));
    }

    public get authentication(): Authentication {
        return (this._authentication ??= new Authentication(this._options));
    }

    public get guardrails(): Guardrails {
        return (this._guardrails ??= new Guardrails(this._options));
    }

    public get strings(): Strings {
        return (this._strings ??= new Strings(this._options));
    }

    public get files(): Files {
        return (this._files ??= new Files(this._options));
    }
}
