/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const SkyflowEnvironment = {
    Production: "https://identifier.vault.skyflowapis.com",
    Sandbox: "https://identifier.vault.skyflowapis-preview.com",
} as const;

export type SkyflowEnvironment = typeof SkyflowEnvironment.Production | typeof SkyflowEnvironment.Sandbox;
