/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Skyflow from "../../../index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Workspaces {
    export interface Options {
        environment?: core.Supplier<environments.SkyflowEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Override the X-Skyflow-Account-ID header */
        skyflowAccountId?: core.Supplier<string | undefined>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the X-Skyflow-Account-ID header */
        skyflowAccountId?: string | undefined;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Workspaces {
    constructor(protected readonly _options: Workspaces.Options = {}) {}

    /**
     * Lists the workspaces in an account.
     *
     * @param {Skyflow.WorkspaceServiceListWorkspacesRequest} request
     * @param {Workspaces.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.workspaces.workspaceServiceListWorkspaces({
     *         accountID: "accountID",
     *         name: "name",
     *         status: "NONE",
     *         offset: "offset",
     *         limit: "limit"
     *     })
     */
    public workspaceServiceListWorkspaces(
        request: Skyflow.WorkspaceServiceListWorkspacesRequest = {},
        requestOptions?: Workspaces.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1ListWorkspacesResponse> {
        return core.HttpResponsePromise.fromPromise(this.__workspaceServiceListWorkspaces(request, requestOptions));
    }

    private async __workspaceServiceListWorkspaces(
        request: Skyflow.WorkspaceServiceListWorkspacesRequest = {},
        requestOptions?: Workspaces.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1ListWorkspacesResponse>> {
        const { accountID: accountId, name, status, offset, limit } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (accountId != null) {
            _queryParams["accountID"] = accountId;
        }

        if (name != null) {
            _queryParams["name"] = name;
        }

        if (status != null) {
            _queryParams["status"] = status;
        }

        if (offset != null) {
            _queryParams["offset"] = offset;
        }

        if (limit != null) {
            _queryParams["limit"] = limit;
        }

        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                "v1/workspaces",
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyflow.V1ListWorkspacesResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError("Timeout exceeded when calling GET /v1/workspaces.");
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Creates a workspace for an account.
     *
     * @param {Skyflow.V1CreateWorkspaceRequest} request
     * @param {Workspaces.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.workspaces.workspaceServiceCreateWorkspace({
     *         workspace: {
     *             name: "LeU",
     *             displayName: "fugiat",
     *             description: "ipsum",
     *             ID: "cillum",
     *             namespace: "ipsum",
     *             contactAddress: {
     *                 streetAddress: "in",
     *                 city: "do incididu",
     *                 state: "nisi Duis consectetur laboris",
     *                 country: "ut labore",
     *                 zip: -62226079
     *             },
     *             status: "NONE",
     *             BasicAudit: {
     *                 CreatedBy: "dolor",
     *                 LastModifiedBy: "incididunt exercitation",
     *                 CreatedOn: "laborum exercitation dolor anim",
     *                 LastModifiedOn: "qui Excepteur"
     *             },
     *             type: "NONE_TYPE",
     *             url: "occaecat tempor dolor",
     *             limits: {
     *                 vaultCountLimit: "1234567890123456789",
     *                 vaultSizeLimit: "1234567890123456789",
     *                 vaultOwnerLimit: "1234567890123456789",
     *                 permissionRestrictions: [{
     *                         roleName: "ad",
     *                         permissions: ["aliqua", "ullamco veniam pariatur", "exercitation"]
     *                     }, {
     *                         roleName: "do consectetur aute ea pariatur",
     *                         permissions: ["sed deserunt sun", "ullamco ipsum veniam", "ve"]
     *                     }, {
     *                         roleName: "exercitation laborum",
     *                         permissions: ["dolor ea consequat do", "sed eu ad amet", "aute "]
     *                     }],
     *                 enableExternalSharing: true
     *             },
     *             regionID: "pariatur ea exer"
     *         },
     *         accountID: "ex ea quis proident fugiat",
     *         regionID: "incididunt est commodo"
     *     })
     */
    public workspaceServiceCreateWorkspace(
        request: Skyflow.V1CreateWorkspaceRequest,
        requestOptions?: Workspaces.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1CreateWorkspaceResponse> {
        return core.HttpResponsePromise.fromPromise(this.__workspaceServiceCreateWorkspace(request, requestOptions));
    }

    private async __workspaceServiceCreateWorkspace(
        request: Skyflow.V1CreateWorkspaceRequest,
        requestOptions?: Workspaces.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1CreateWorkspaceResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                "v1/workspaces",
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyflow.V1CreateWorkspaceResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError("Timeout exceeded when calling POST /v1/workspaces.");
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Returns the specified workspace.
     *
     * @param {string} id - ID of the workspace.
     * @param {Workspaces.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.workspaces.workspaceServiceGetWorkspace("ID")
     */
    public workspaceServiceGetWorkspace(
        id: string,
        requestOptions?: Workspaces.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1GetWorkspaceResponse> {
        return core.HttpResponsePromise.fromPromise(this.__workspaceServiceGetWorkspace(id, requestOptions));
    }

    private async __workspaceServiceGetWorkspace(
        id: string,
        requestOptions?: Workspaces.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1GetWorkspaceResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                `v1/workspaces/${encodeURIComponent(id)}`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyflow.V1GetWorkspaceResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError("Timeout exceeded when calling GET /v1/workspaces/{ID}.");
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Deletes the specified Workspace and the entities it contains.
     *
     * @param {string} id - ID of the workspace.
     * @param {Workspaces.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.workspaces.workspaceServiceDeleteWorkspace("ID")
     */
    public workspaceServiceDeleteWorkspace(
        id: string,
        requestOptions?: Workspaces.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1DeleteWorkspaceResponse> {
        return core.HttpResponsePromise.fromPromise(this.__workspaceServiceDeleteWorkspace(id, requestOptions));
    }

    private async __workspaceServiceDeleteWorkspace(
        id: string,
        requestOptions?: Workspaces.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1DeleteWorkspaceResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                `v1/workspaces/${encodeURIComponent(id)}`,
            ),
            method: "DELETE",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyflow.V1DeleteWorkspaceResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError("Timeout exceeded when calling DELETE /v1/workspaces/{ID}.");
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Updates the specified Workspace.
     *
     * @param {string} id - ID of the workspace.
     * @param {Skyflow.WorkspaceServiceUpdateWorkspaceBody} request
     * @param {Workspaces.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.workspaces.workspaceServiceUpdateWorkspace("ID", {
     *         workspace: {
     *             name: "AZ6oth9",
     *             displayName: "veniam",
     *             description: "ea culpa eu enim magna",
     *             ID: "tempor deser",
     *             namespace: "mollit amet ad",
     *             contactAddress: {
     *                 streetAddress: "anim",
     *                 city: "veniam",
     *                 state: "consectetur",
     *                 country: "minim velit eu esse",
     *                 zip: 29611615
     *             },
     *             status: "NONE",
     *             BasicAudit: {
     *                 CreatedBy: "aute anim",
     *                 LastModifiedBy: "in ut ex",
     *                 CreatedOn: "Duis enim culpa fugiat ",
     *                 LastModifiedOn: ""
     *             },
     *             type: "NONE_TYPE",
     *             url: "non qui ea c",
     *             limits: {
     *                 vaultCountLimit: "1234567890123456789",
     *                 vaultSizeLimit: "1234567890123456789",
     *                 vaultOwnerLimit: "1234567890123456789",
     *                 permissionRestrictions: [{
     *                         roleName: "",
     *                         permissions: ["consequat sint velit", "labore ut ", "tempor Ut"]
     *                     }, {
     *                         roleName: "commodo pariatur aliqua",
     *                         permissions: ["eu", "in consectetur do ipsum", ""]
     *                     }, {
     *                         roleName: "eu",
     *                         permissions: ["qui exercitation cupidatat ad nostrud", "eu do aliqua sed", "do sint adipisicing offic"]
     *                     }],
     *                 enableExternalSharing: true
     *             },
     *             regionID: "magna Lorem sint ipsum culp"
     *         }
     *     })
     */
    public workspaceServiceUpdateWorkspace(
        id: string,
        request: Skyflow.WorkspaceServiceUpdateWorkspaceBody = {},
        requestOptions?: Workspaces.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1UpdateWorkspaceResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__workspaceServiceUpdateWorkspace(id, request, requestOptions),
        );
    }

    private async __workspaceServiceUpdateWorkspace(
        id: string,
        request: Skyflow.WorkspaceServiceUpdateWorkspaceBody = {},
        requestOptions?: Workspaces.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1UpdateWorkspaceResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                `v1/workspaces/${encodeURIComponent(id)}`,
            ),
            method: "PATCH",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyflow.V1UpdateWorkspaceResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError("Timeout exceeded when calling PATCH /v1/workspaces/{ID}.");
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Lists members for the specified workspace.
     *
     * @param {string} id - ID of the resource. For example, if the resource is `roles`, this field is the role ID. If the resource is `workspaces`, this field is the workspace ID.
     * @param {Skyflow.WorkspaceServiceListMembersRequest} request
     * @param {Workspaces.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.NotFoundError}
     *
     * @example
     *     await client.workspaces.workspaceServiceListMembers("ID", {
     *         "filterOps.email": "filterOps.email",
     *         "filterOps.type": "NONE",
     *         "filterOps.name": "filterOps.name",
     *         "filterOps.status": "NONE",
     *         "sortOps.sortBy": "sortOps.sortBy",
     *         "sortOps.orderBy": "ASCENDING",
     *         offset: "offset",
     *         limit: "limit"
     *     })
     */
    public workspaceServiceListMembers(
        id: string,
        request: Skyflow.WorkspaceServiceListMembersRequest = {},
        requestOptions?: Workspaces.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.V1ListMembersResponse> {
        return core.HttpResponsePromise.fromPromise(this.__workspaceServiceListMembers(id, request, requestOptions));
    }

    private async __workspaceServiceListMembers(
        id: string,
        request: Skyflow.WorkspaceServiceListMembersRequest = {},
        requestOptions?: Workspaces.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.V1ListMembersResponse>> {
        const {
            "filterOps.email": filterOpsEmail,
            "filterOps.type": filterOpsType,
            "filterOps.name": filterOpsName,
            "filterOps.status": filterOpsStatus,
            "sortOps.sortBy": sortOpsSortBy,
            "sortOps.orderBy": sortOpsOrderBy,
            offset,
            limit,
        } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (filterOpsEmail != null) {
            _queryParams["filterOps.email"] = filterOpsEmail;
        }

        if (filterOpsType != null) {
            _queryParams["filterOps.type"] = filterOpsType;
        }

        if (filterOpsName != null) {
            _queryParams["filterOps.name"] = filterOpsName;
        }

        if (filterOpsStatus != null) {
            _queryParams["filterOps.status"] = filterOpsStatus;
        }

        if (sortOpsSortBy != null) {
            _queryParams["sortOps.sortBy"] = sortOpsSortBy;
        }

        if (sortOpsOrderBy != null) {
            _queryParams["sortOps.orderBy"] = sortOpsOrderBy;
        }

        if (offset != null) {
            _queryParams["offset"] = offset;
        }

        if (limit != null) {
            _queryParams["limit"] = limit;
        }

        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                `v1/workspaces/${encodeURIComponent(id)}/members`,
            ),
            method: "GET",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Skyflow-Account-ID":
                    (await core.Supplier.get(this._options.skyflowAccountId)) != null
                        ? await core.Supplier.get(this._options.skyflowAccountId)
                        : undefined,
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            queryParameters: _queryParams,
            requestType: "json",
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyflow.V1ListMembersResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new Skyflow.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError("Timeout exceeded when calling GET /v1/workspaces/{ID}/members.");
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
