/* tslint:disable */
/* eslint-disable */
/**
 * Skyflow Data API
 * # Data API  This API inserts, retrieves, and otherwise manages data in a vault.  The Data API is available from two base URIs. *identifier* is the identifier in your vault\'s URL.<ul><li><b>Sandbox:</b> https://_*identifier*.vault.skyflowapis-preview.com</li><li><b>Production:</b> https://_*identifier*.vault.skyflowapis.com</li></ul>  When you make an API call, you need to add a header: <table><tr><th>Header</th><th>Value</th><th>Example</th></tr><tr><td>Authorization</td><td>A Bearer Token. See <a href=\'/api-authentication/\'>API Authentication</a>.</td><td><code>Authorization: Bearer eyJhbGciOiJSUzI...1NiIsJdfPA</code></td></tr><table/>
 *
 * The version of the OpenAPI document: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GooglerpcStatus } from '../models';
// @ts-ignore
import type { QueryServiceExecuteQueryBody } from '../models';
// @ts-ignore
import type { V1GetQueryResponse } from '../models';
/**
 * QueryApi - axios parameter creator
 * @export
 */
export const QueryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns records for a valid SQL query. This endpoint <ul><li>Can return redacted record values.</li><li>Supports only the <code>SELECT</code> command.</li><li>Returns a maximum of 25 records. To return additional records, perform another query using the <code>OFFSET</code> keyword.</li><li>Can\'t modify the vault or perform transactions.</li><li>Can\'t return tokens.</li><li>Can\'t return file download or render URLs.</li><li>Doesn\'t support the <code>WHERE</code> keyword with columns using transient tokenization.</li><li>Doesn\'t support `?` conditional for columns with column-level encryption disabled.</li><ul>
         * @summary Execute Query
         * @param {string} vaultID ID of the vault.
         * @param {QueryServiceExecuteQueryBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryServiceExecuteQuery: async (vaultID: string, body: QueryServiceExecuteQueryBody, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'vaultID' is not null or undefined
            assertParamExists('queryServiceExecuteQuery', 'vaultID', vaultID)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('queryServiceExecuteQuery', 'body', body)
            const localVarPath = `/v1/vaults/{vaultID}/query`
                .replace(`{${"vaultID"}}`, encodeURIComponent(String(vaultID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QueryApi - functional programming interface
 * @export
 */
export const QueryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QueryApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns records for a valid SQL query. This endpoint <ul><li>Can return redacted record values.</li><li>Supports only the <code>SELECT</code> command.</li><li>Returns a maximum of 25 records. To return additional records, perform another query using the <code>OFFSET</code> keyword.</li><li>Can\'t modify the vault or perform transactions.</li><li>Can\'t return tokens.</li><li>Can\'t return file download or render URLs.</li><li>Doesn\'t support the <code>WHERE</code> keyword with columns using transient tokenization.</li><li>Doesn\'t support `?` conditional for columns with column-level encryption disabled.</li><ul>
         * @summary Execute Query
         * @param {string} vaultID ID of the vault.
         * @param {QueryServiceExecuteQueryBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async queryServiceExecuteQuery(vaultID: string, body: QueryServiceExecuteQueryBody, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1GetQueryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.queryServiceExecuteQuery(vaultID, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QueryApi.queryServiceExecuteQuery']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QueryApi - factory interface
 * @export
 */
export const QueryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QueryApiFp(configuration)
    return {
        /**
         * Returns records for a valid SQL query. This endpoint <ul><li>Can return redacted record values.</li><li>Supports only the <code>SELECT</code> command.</li><li>Returns a maximum of 25 records. To return additional records, perform another query using the <code>OFFSET</code> keyword.</li><li>Can\'t modify the vault or perform transactions.</li><li>Can\'t return tokens.</li><li>Can\'t return file download or render URLs.</li><li>Doesn\'t support the <code>WHERE</code> keyword with columns using transient tokenization.</li><li>Doesn\'t support `?` conditional for columns with column-level encryption disabled.</li><ul>
         * @summary Execute Query
         * @param {string} vaultID ID of the vault.
         * @param {QueryServiceExecuteQueryBody} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        queryServiceExecuteQuery(vaultID: string, body: QueryServiceExecuteQueryBody, options?: RawAxiosRequestConfig): AxiosPromise<V1GetQueryResponse> {
            return localVarFp.queryServiceExecuteQuery(vaultID, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QueryApi - interface
 * @export
 * @interface QueryApi
 */
export interface QueryApiInterface {
    /**
     * Returns records for a valid SQL query. This endpoint <ul><li>Can return redacted record values.</li><li>Supports only the <code>SELECT</code> command.</li><li>Returns a maximum of 25 records. To return additional records, perform another query using the <code>OFFSET</code> keyword.</li><li>Can\'t modify the vault or perform transactions.</li><li>Can\'t return tokens.</li><li>Can\'t return file download or render URLs.</li><li>Doesn\'t support the <code>WHERE</code> keyword with columns using transient tokenization.</li><li>Doesn\'t support `?` conditional for columns with column-level encryption disabled.</li><ul>
     * @summary Execute Query
     * @param {string} vaultID ID of the vault.
     * @param {QueryServiceExecuteQueryBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QueryApiInterface
     */
    queryServiceExecuteQuery(vaultID: string, body: QueryServiceExecuteQueryBody, options?: RawAxiosRequestConfig): AxiosPromise<V1GetQueryResponse>;

}

/**
 * QueryApi - object-oriented interface
 * @export
 * @class QueryApi
 * @extends {BaseAPI}
 */
export class QueryApi extends BaseAPI implements QueryApiInterface {
    /**
     * Returns records for a valid SQL query. This endpoint <ul><li>Can return redacted record values.</li><li>Supports only the <code>SELECT</code> command.</li><li>Returns a maximum of 25 records. To return additional records, perform another query using the <code>OFFSET</code> keyword.</li><li>Can\'t modify the vault or perform transactions.</li><li>Can\'t return tokens.</li><li>Can\'t return file download or render URLs.</li><li>Doesn\'t support the <code>WHERE</code> keyword with columns using transient tokenization.</li><li>Doesn\'t support `?` conditional for columns with column-level encryption disabled.</li><ul>
     * @summary Execute Query
     * @param {string} vaultID ID of the vault.
     * @param {QueryServiceExecuteQueryBody} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QueryApi
     */
    public queryServiceExecuteQuery(vaultID: string, body: QueryServiceExecuteQueryBody, options?: RawAxiosRequestConfig) {
        return QueryApiFp(this.configuration).queryServiceExecuteQuery(vaultID, body, options).then((request) => request(this.axios, this.basePath));
    }
}

