/* tslint:disable */
/* eslint-disable */
/**
 * Skyflow Data API
 * # Data API  This API inserts, retrieves, and otherwise manages data in a vault.  The Data API is available from two base URIs. *identifier* is the identifier in your vault\'s URL.<ul><li><b>Sandbox:</b> https://_*identifier*.vault.skyflowapis-preview.com</li><li><b>Production:</b> https://_*identifier*.vault.skyflowapis.com</li></ul>  When you make an API call, you need to add a header: <table><tr><th>Header</th><th>Value</th><th>Example</th></tr><tr><td>Authorization</td><td>A Bearer Token. See <a href=\'/api-authentication/\'>API Authentication</a>.</td><td><code>Authorization: Bearer eyJhbGciOiJSUzI...1NiIsJdfPA</code></td></tr><table/>
 *
 * The version of the OpenAPI document: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GooglerpcStatus } from '../models';
// @ts-ignore
import type { V1DetokenizePayload } from '../models';
// @ts-ignore
import type { V1DetokenizeResponse } from '../models';
// @ts-ignore
import type { V1TokenizePayload } from '../models';
// @ts-ignore
import type { V1TokenizeResponse } from '../models';
/**
 * TokensApi - axios parameter creator
 * @export
 */
export const TokensApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns records that correspond to the specified tokens.
         * @summary Detokenize
         * @param {string} vaultID ID of the vault.
         * @param {V1DetokenizePayload} detokenizePayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordServiceDetokenize: async (vaultID: string, detokenizePayload: V1DetokenizePayload, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'vaultID' is not null or undefined
            assertParamExists('recordServiceDetokenize', 'vaultID', vaultID)
            // verify required parameter 'detokenizePayload' is not null or undefined
            assertParamExists('recordServiceDetokenize', 'detokenizePayload', detokenizePayload)
            const localVarPath = `/v1/vaults/{vaultID}/detokenize`
                .replace(`{${"vaultID"}}`, encodeURIComponent(String(vaultID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(detokenizePayload, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns tokens that correspond to the specified records. Only applicable for fields with deterministic tokenization.<br /><br /><b>Note:</b> This endpoint doesn\'t insert records—it returns tokens for existing values. To insert records and tokenize that new record\'s values, see <a href=\'#RecordService_InsertRecord\'>Insert Record</a> and the tokenization parameter.
         * @summary Tokenize
         * @param {string} vaultID ID of the vault.
         * @param {V1TokenizePayload} tokenizePayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordServiceTokenize: async (vaultID: string, tokenizePayload: V1TokenizePayload, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'vaultID' is not null or undefined
            assertParamExists('recordServiceTokenize', 'vaultID', vaultID)
            // verify required parameter 'tokenizePayload' is not null or undefined
            assertParamExists('recordServiceTokenize', 'tokenizePayload', tokenizePayload)
            const localVarPath = `/v1/vaults/{vaultID}/tokenize`
                .replace(`{${"vaultID"}}`, encodeURIComponent(String(vaultID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(tokenizePayload, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TokensApi - functional programming interface
 * @export
 */
export const TokensApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TokensApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns records that correspond to the specified tokens.
         * @summary Detokenize
         * @param {string} vaultID ID of the vault.
         * @param {V1DetokenizePayload} detokenizePayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recordServiceDetokenize(vaultID: string, detokenizePayload: V1DetokenizePayload, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1DetokenizeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recordServiceDetokenize(vaultID, detokenizePayload, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TokensApi.recordServiceDetokenize']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns tokens that correspond to the specified records. Only applicable for fields with deterministic tokenization.<br /><br /><b>Note:</b> This endpoint doesn\'t insert records—it returns tokens for existing values. To insert records and tokenize that new record\'s values, see <a href=\'#RecordService_InsertRecord\'>Insert Record</a> and the tokenization parameter.
         * @summary Tokenize
         * @param {string} vaultID ID of the vault.
         * @param {V1TokenizePayload} tokenizePayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recordServiceTokenize(vaultID: string, tokenizePayload: V1TokenizePayload, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1TokenizeResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recordServiceTokenize(vaultID, tokenizePayload, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TokensApi.recordServiceTokenize']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TokensApi - factory interface
 * @export
 */
export const TokensApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TokensApiFp(configuration)
    return {
        /**
         * Returns records that correspond to the specified tokens.
         * @summary Detokenize
         * @param {string} vaultID ID of the vault.
         * @param {V1DetokenizePayload} detokenizePayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordServiceDetokenize(vaultID: string, detokenizePayload: V1DetokenizePayload, options?: RawAxiosRequestConfig): AxiosPromise<V1DetokenizeResponse> {
            return localVarFp.recordServiceDetokenize(vaultID, detokenizePayload, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns tokens that correspond to the specified records. Only applicable for fields with deterministic tokenization.<br /><br /><b>Note:</b> This endpoint doesn\'t insert records—it returns tokens for existing values. To insert records and tokenize that new record\'s values, see <a href=\'#RecordService_InsertRecord\'>Insert Record</a> and the tokenization parameter.
         * @summary Tokenize
         * @param {string} vaultID ID of the vault.
         * @param {V1TokenizePayload} tokenizePayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordServiceTokenize(vaultID: string, tokenizePayload: V1TokenizePayload, options?: RawAxiosRequestConfig): AxiosPromise<V1TokenizeResponse> {
            return localVarFp.recordServiceTokenize(vaultID, tokenizePayload, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TokensApi - interface
 * @export
 * @interface TokensApi
 */
export interface TokensApiInterface {
    /**
     * Returns records that correspond to the specified tokens.
     * @summary Detokenize
     * @param {string} vaultID ID of the vault.
     * @param {V1DetokenizePayload} detokenizePayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokensApiInterface
     */
    recordServiceDetokenize(vaultID: string, detokenizePayload: V1DetokenizePayload, options?: RawAxiosRequestConfig): AxiosPromise<V1DetokenizeResponse>;

    /**
     * Returns tokens that correspond to the specified records. Only applicable for fields with deterministic tokenization.<br /><br /><b>Note:</b> This endpoint doesn\'t insert records—it returns tokens for existing values. To insert records and tokenize that new record\'s values, see <a href=\'#RecordService_InsertRecord\'>Insert Record</a> and the tokenization parameter.
     * @summary Tokenize
     * @param {string} vaultID ID of the vault.
     * @param {V1TokenizePayload} tokenizePayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokensApiInterface
     */
    recordServiceTokenize(vaultID: string, tokenizePayload: V1TokenizePayload, options?: RawAxiosRequestConfig): AxiosPromise<V1TokenizeResponse>;

}

/**
 * TokensApi - object-oriented interface
 * @export
 * @class TokensApi
 * @extends {BaseAPI}
 */
export class TokensApi extends BaseAPI implements TokensApiInterface {
    /**
     * Returns records that correspond to the specified tokens.
     * @summary Detokenize
     * @param {string} vaultID ID of the vault.
     * @param {V1DetokenizePayload} detokenizePayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokensApi
     */
    public recordServiceDetokenize(vaultID: string, detokenizePayload: V1DetokenizePayload, options?: RawAxiosRequestConfig) {
        return TokensApiFp(this.configuration).recordServiceDetokenize(vaultID, detokenizePayload, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns tokens that correspond to the specified records. Only applicable for fields with deterministic tokenization.<br /><br /><b>Note:</b> This endpoint doesn\'t insert records—it returns tokens for existing values. To insert records and tokenize that new record\'s values, see <a href=\'#RecordService_InsertRecord\'>Insert Record</a> and the tokenization parameter.
     * @summary Tokenize
     * @param {string} vaultID ID of the vault.
     * @param {V1TokenizePayload} tokenizePayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TokensApi
     */
    public recordServiceTokenize(vaultID: string, tokenizePayload: V1TokenizePayload, options?: RawAxiosRequestConfig) {
        return TokensApiFp(this.configuration).recordServiceTokenize(vaultID, tokenizePayload, options).then((request) => request(this.axios, this.basePath));
    }
}

