/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         userEmail: "userEmail",
 *         name: "name",
 *         status: "NONE",
 *         offset: "offset",
 *         limit: "limit",
 *         accountID: "accountID"
 *     }
 */
export interface AccountServiceListAccountsRequest {
    /**
     * Filter that limits returned accounts to those that include the specified email address.
     */
    userEmail?: string;
    /**
     * Filter that limits returned accounts to those that include the specified name.
     */
    name?: string;
    /**
     * Filter that limits returned accounts to those that match the specified status.
     */
    status?: Skyflow.AccountServiceListAccountsRequestStatus;
    /**
     * Record position at which to start retrieving accounts.
     */
    offset?: string;
    /**
     * Number of accounts to retrieve.
     */
    limit?: string;
    /**
     * Filter that limits accounts to those that are children of the specified account ID.
     */
    accountID?: string;
}
