/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         "resource.ID": "resource.ID",
 *         "resource.type": "NONE",
 *         "resource.name": "resource.name",
 *         "resource.namespace": "resource.namespace",
 *         "resource.description": "resource.description",
 *         "resource.status": "NONE",
 *         "resource.displayName": "resource.displayName",
 *         offset: "offset",
 *         limit: "limit"
 *     }
 */
export interface AccountServiceListResourcesRequest {
    /**
     * ID of the resource. For example, if `resource.type` is `VAULT`, this field is the vault ID. If `resource.type` is `WORKSPACE`, this field is the workspace ID.
     */
    "resource.ID": string;
    /**
     * Type of the resource.
     */
    "resource.type": Skyflow.AccountServiceListResourcesRequestResourceType;
    /**
     * Name of the resource.
     */
    "resource.name"?: string;
    /**
     * Unique namespace for the resource. Generated by Skyflow.
     */
    "resource.namespace"?: string;
    /**
     * Description of the resource.
     */
    "resource.description"?: string;
    /**
     * Status of the resource.
     */
    "resource.status"?: Skyflow.AccountServiceListResourcesRequestResourceStatus;
    /**
     * Display name of the resource that appears in user interfaces.
     */
    "resource.displayName"?: string;
    /**
     * Record position at which to start receiving results.
     */
    offset?: string;
    /**
     * Number of results to return.
     */
    limit?: string;
}
