/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         account: {
 *             name: "ld9to",
 *             displayName: "ut sit non",
 *             description: "ullamco labore nulla irure enim",
 *             ID: "ad fugiat sed veli",
 *             namespace: "cons",
 *             contactAddress: {
 *                 streetAddress: "officia sint velit",
 *                 city: "laborum ex deserunt nisi Excepteur",
 *                 state: "occaecat voluptate enim",
 *                 country: "occaecat",
 *                 zip: -82629808
 *             },
 *             BasicAudit: {
 *                 CreatedBy: "reprehenderit Lorem velit exercitation deserunt",
 *                 LastModifiedBy: "velit nisi",
 *                 CreatedOn: "proident",
 *                 LastModifiedOn: "aliquip nisi esse"
 *             },
 *             status: "NONE",
 *             tenantType: "NONE_TYPE",
 *             accountType: "TYPE_NONE"
 *         }
 *     }
 */
export interface AccountServiceUpdateAccountBody {
    account?: Skyflow.V1Account;
}
