/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "reprehenderit",
 *         description: "cupidatat in esse ipsum",
 *         functionID: "enim dolore dolor aliquip",
 *         versionTag: "est adipisicing",
 *         functionEnvironmentID: "dolor laboris enim ea"
 *     }
 */
export interface FunctionServiceUpdateFunctionDeploymentBody {
    /** Name of the deployment. */
    name?: string;
    /** Description of the deployment. */
    description?: string;
    /** ID of the function. */
    functionID?: string;
    /** Version of the function. */
    versionTag?: string;
    /** ID of the environment to deploy the function in. */
    functionEnvironmentID?: string;
}
