/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         "sortOps.sortBy": "sortOps.sortBy",
 *         "sortOps.orderBy": "ASCENDING",
 *         offset: "offset",
 *         limit: "limit"
 *     }
 */
export interface FunctionServiceListFunctionRequest {
    /**
     * Fully-qualified field by which to sort results. Field names should be in camel case (for example, "capitalization.camelCase").
     */
    "sortOps.sortBy"?: string;
    /**
     * Ascending or descending ordering of results.
     */
    "sortOps.orderBy"?: Skyflow.FunctionServiceListFunctionRequestSortOpsOrderBy;
    /**
     * Record position at which to start receiving results.
     */
    offset?: string;
    /**
     * Number of results to return.
     */
    limit?: string;
}
