/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         verbose: true
 *     }
 */
export interface FunctionServiceGetFunctionDeploymentRequest {
    /**
     * If <code>true</code>, creates the verbose function deployment logs.
     */
    verbose?: boolean;
}
