/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         name: "veniam id enim ut tempor",
 *         description: "sit labore",
 *         code: "aute",
 *         functionConfigs: [{
 *                 handlerName: "consectetur mollit",
 *                 methodName: "ad in",
 *                 variables: [{
 *                         name: "consequat",
 *                         value: "laboris mollit veniam deserunt pariatur",
 *                         type: "NONE"
 *                     }, {
 *                         name: "sint officia irure Lorem Ut",
 *                         value: "sunt laborum et",
 *                         type: "NONE"
 *                     }, {
 *                         name: "laborum",
 *                         value: "sit do labore tempor",
 *                         type: "NONE"
 *                     }],
 *                 resourceConfig: {
 *                     timeout: 78105389,
 *                     memory: -77146941
 *                 },
 *                 numberOfWarmInstances: -23769579
 *             }, {
 *                 handlerName: "est ven",
 *                 methodName: "fugiat dolor Duis aliqua",
 *                 variables: [{
 *                         name: "est deserunt Lorem",
 *                         value: "aliquip sit deserunt in",
 *                         type: "NONE"
 *                     }, {
 *                         name: "aliqua pariatur Excepteur",
 *                         value: "commodo aliquip dolor",
 *                         type: "NONE"
 *                     }, {
 *                         name: "voluptate minim",
 *                         value: "amet culpa",
 *                         type: "NONE"
 *                     }],
 *                 resourceConfig: {
 *                     timeout: -62010697,
 *                     memory: 2251862
 *                 },
 *                 numberOfWarmInstances: 58524072
 *             }, {
 *                 handlerName: "ea proi",
 *                 methodName: "ut nulla ipsum Excepteur",
 *                 variables: [{
 *                         name: "sit cillum",
 *                         value: "ipsum anim consectetur laboris enim",
 *                         type: "NONE"
 *                     }, {
 *                         name: "cupidatat ut consectetur",
 *                         value: "elit officia aute ea",
 *                         type: "NONE"
 *                     }, {
 *                         name: "aliqua laboris irure mollit",
 *                         value: "mollit ex ut ad",
 *                         type: "NONE"
 *                     }],
 *                 resourceConfig: {
 *                     timeout: -23357207,
 *                     memory: -56585675
 *                 },
 *                 numberOfWarmInstances: 86244839
 *             }],
 *         functionDeployment: {
 *             deploy: true,
 *             functionEnvironmentID: "in",
 *             regionID: "ea",
 *             functionDeploymentName: "eiusmod officia commodo",
 *             functionDeploymentDescription: "sed adipisicing magna officia"
 *         },
 *         language: {
 *             languageName: "LANGUAGE_NOT_DEFINED",
 *             languageVersion: "mollit enim"
 *         },
 *         dependencies: ["proident aute occaecat incididunt in", "aute sunt nisi", "commodo veniam Lorem"]
 *     }
 */
export interface FunctionServiceUpdateFunctionBody {
    /** Name of the function. */
    name?: string;
    /** Description of the function. */
    description?: string;
    /** Function code snippet as string. */
    code?: string;
    /** Function handler configuration details. */
    functionConfigs?: Skyflow.V1HandlerConfig[];
    functionDeployment?: Skyflow.V1FunctionDeploymentConfig;
    language?: Skyflow.V1FunctionLanguage;
    /** Required libraries for the function. */
    dependencies?: string[];
}
