/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         name: "exercitation velit",
 *         description: "non in ut commodo ipsum",
 *         code: "dolore mollit",
 *         functionConfigs: [{
 *                 handlerName: "reprehenderit id do ullamco",
 *                 methodName: "amet Excepteur nisi dolore enim",
 *                 variables: [{
 *                         name: "Ut ad nulla commodo",
 *                         value: "ad eiusmod",
 *                         type: "NONE"
 *                     }, {
 *                         name: "ullamco aliquip sit",
 *                         value: "qu",
 *                         type: "NONE"
 *                     }, {
 *                         name: "irure",
 *                         value: "nulla voluptate est",
 *                         type: "NONE"
 *                     }],
 *                 resourceConfig: {
 *                     timeout: -9565061,
 *                     memory: 33475922
 *                 },
 *                 numberOfWarmInstances: -95061544
 *             }, {
 *                 handlerName: "",
 *                 methodName: "magna dolor Duis",
 *                 variables: [{
 *                         name: "proident",
 *                         value: "tempor occaecat mollit",
 *                         type: "NONE"
 *                     }, {
 *                         name: "et fugiat incididunt",
 *                         value: "in",
 *                         type: "NONE"
 *                     }, {
 *                         name: "ad ut consectetur do ipsum",
 *                         value: "veniam tempor dolore ea",
 *                         type: "NONE"
 *                     }],
 *                 resourceConfig: {
 *                     timeout: 25178660,
 *                     memory: -94985779
 *                 },
 *                 numberOfWarmInstances: 77344281
 *             }, {
 *                 handlerName: "reprehenderit ut sed quis off",
 *                 methodName: "culpa id quis pariatur",
 *                 variables: [{
 *                         name: "reprehenderit",
 *                         value: "commodo reprehenderit consectetur Lorem in",
 *                         type: "NONE"
 *                     }, {
 *                         name: "dolore",
 *                         value: "aliquip sint laborum",
 *                         type: "NONE"
 *                     }, {
 *                         name: "ea et enim ad amet",
 *                         value: "ad quis aliqua consequat nostrud",
 *                         type: "NONE"
 *                     }],
 *                 resourceConfig: {
 *                     timeout: 30590744,
 *                     memory: 98286963
 *                 },
 *                 numberOfWarmInstances: -40007065
 *             }],
 *         functionDeployment: {
 *             deploy: true,
 *             functionEnvironmentID: "cupidatat sunt pariatur consequat",
 *             regionID: "non in sit aliquip",
 *             functionDeploymentName: "ea elit",
 *             functionDeploymentDescription: "nulla in incididunt"
 *         },
 *         language: {
 *             languageName: "LANGUAGE_NOT_DEFINED",
 *             languageVersion: "consectetur dolor culpa aute quis"
 *         },
 *         dependencies: ["velit", "voluptate", "culpa amet laborum nisi ea"]
 *     }
 */
export interface V1CreateFunctionRequest {
    /** Name of the function. */
    name?: string;
    /** Description of the function. */
    description?: string;
    /** Function code snippet as string. */
    code?: string;
    /** Function handler configuration details. */
    functionConfigs?: Skyflow.V1HandlerConfig[];
    functionDeployment?: Skyflow.V1FunctionDeploymentConfig;
    language?: Skyflow.V1FunctionLanguage;
    /** Required libraries for the function. */
    dependencies?: string[];
}
