/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Contains map of what entity has to be stored in which column.
 */
export interface AdvancedOptionsEntityColumnMap {
    entity_type?: Skyflow.DetectDataEntities;
    /** Column name where the entity has to be stored. */
    column_name?: string;
}
