/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Contains table name and column mapping.
 */
export interface AdvancedOptionsVaultSchema {
    /** Table name of the vault. */
    table_name: string;
    mapping: Skyflow.AdvancedOptionsColumnMapping;
}
