/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AuditEventHttpInfo {
    /** The http URI that is used. */
    URI?: string;
    /** http method used. */
    method?: string;
}
