/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Context for an audit event.
 */
export interface AuditEventContext {
    /** ID for the audit event. */
    changeID?: string;
    /** ID for the request that caused the event. */
    requestID?: string;
    /** ID for the request set by the service that received the request. */
    traceID?: string;
    /** ID for the session in which the request was sent. */
    sessionID?: string;
    /** Member who sent the request. Depending on `actorType`, this may be a user ID or a service account ID. */
    actor?: string;
    actorType?: Skyflow.V1MemberType;
    accessType?: Skyflow.ContextAccessType;
    /** IP Address of the client that made the request. */
    ipAddress?: string;
    /** HTTP Origin request header (including scheme, hostname, and port) of the request. */
    origin?: string;
    authMode?: Skyflow.ContextAuthMode;
    /** ID of the JWT token. */
    jwtID?: string;
    /** Embedded User Context. */
    bearerTokenContextID?: string;
}
