/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Response to deidentify a string.
 */
export interface DeidentifyStringResponse {
    /** De-identified text. */
    processed_text: string;
    /** Detected entities. */
    entities: Skyflow.DetectedEntity[];
    /** Number of words from the input text. */
    word_count: number;
    /** Number of characters from the input text. */
    character_count: number;
}
