/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status of the detect run.
 */
export type DeidentifyStatusResponseStatus = "FAILED" | "IN_PROGRESS" | "SUCCESS";
export const DeidentifyStatusResponseStatus = {
    Failed: "FAILED",
    InProgress: "IN_PROGRESS",
    Success: "SUCCESS",
} as const;
