/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Response to get the status of a detect run.
 */
export interface DeidentifyStatusResponse {
    /** Status of the detect run. */
    status: Skyflow.DeidentifyStatusResponseStatus;
    /** How the input file was specified. */
    output: Skyflow.DeidentifyFileOutput[];
    /** How the output file is specified. */
    output_type?: Skyflow.DeidentifyStatusResponseOutputType;
    /** Status details about the detect run. */
    message: string;
    /** Number of words in the processed text. */
    word_count?: number;
    /** Number of characters in the processed text. */
    character_count?: number;
    /** Size of the processed text in kilobytes (KB). */
    size?: number;
    /** Duration of the processed audio in seconds. */
    duration?: number;
    /** Number of pages in the processed PDF. */
    pages?: number;
    /** Number of slides in the processed presentation. */
    slides?: number;
}
