/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of the processed file.
 */
export type DeidentifyFileOutputProcessedFileType =
    | "entities"
    | "plaintext_transcription"
    | "redacted_audio"
    | "redacted_diarized_transcription"
    | "redacted_file"
    | "redacted_image"
    | "redacted_medical_diarized_transcription"
    | "redacted_medical_transcription"
    | "redacted_text"
    | "redacted_transcription";
export const DeidentifyFileOutputProcessedFileType = {
    Entities: "entities",
    PlaintextTranscription: "plaintext_transcription",
    RedactedAudio: "redacted_audio",
    RedactedDiarizedTranscription: "redacted_diarized_transcription",
    RedactedFile: "redacted_file",
    RedactedImage: "redacted_image",
    RedactedMedicalDiarizedTranscription: "redacted_medical_diarized_transcription",
    RedactedMedicalTranscription: "redacted_medical_transcription",
    RedactedText: "redacted_text",
    RedactedTranscription: "redacted_transcription",
} as const;
