/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * How the output file is specified.
 */
export type DeidentifyStatusResponseOutputType = "BASE64" | "EFS_PATH" | "UNKNOWN";
export const DeidentifyStatusResponseOutputType = {
    Base64: "BASE64",
    EfsPath: "EFS_PATH",
    Unknown: "UNKNOWN",
} as const;
