/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of token to generate for detected entities.
 *
 *  - UNKNOWN: unknown.
 *  - ENTITY_UNQ_COUNTER: Sensitive words are replaced with the entity type and a unique number. For example, "John and Jane" becomes "[NAME_1] and [NAME_2]".
 *  - ENTITY_ONLY: Sensitive words are replaced with the entity type. For example, "John and Jane" becomes "[NAME] and [NAME]".
 */
export type DetectRequestDeidentifyOption = "UNKNOWN" | "ENTITY_UNQ_COUNTER" | "ENTITY_ONLY";
export const DetectRequestDeidentifyOption = {
    Unknown: "UNKNOWN",
    EntityUnqCounter: "ENTITY_UNQ_COUNTER",
    EntityOnly: "ENTITY_ONLY",
} as const;
