/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * How the input file is specified.
 *
 *  - UNKNOWN: Unknown data type.
 *  - BASE64: Base64 encoded data.
 */
export type DetectFileRequestDataType = "UNKNOWN" | "BASE64";
export const DetectFileRequestDataType = {
    Unknown: "UNKNOWN",
    Base64: "BASE64",
} as const;
