/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Response to re-identify a file.
 */
export interface ReidentifyFileResponse {
    /** Status of the re-identify operation. */
    status: Skyflow.ReidentifyFileResponseStatus;
    /** Format of the output file. */
    output_type: "BASE64";
    output: Skyflow.ReidentifyFileResponseOutput;
}
