/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TransformationsShiftDatesEntityTypesItem = "date" | "date_interval" | "dob";
export const TransformationsShiftDatesEntityTypesItem = {
    Date: "date",
    DateInterval: "date_interval",
    Dob: "dob",
} as const;
