/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * How to handle audio files.
 */
export interface V1AudioConfig {
    output_transcription?: Skyflow.AudioConfigTranscriptionType;
    /** If `true`, includes processed audio file in the response. */
    output_processed_audio?: boolean;
    options?: Skyflow.V1AudioOptions;
}
