/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface V1AuditAfterOptions {
    /** Timestamp provided in the previous audit response's `nextOps` attribute. An alternate way to manage response pagination. Can't be used with `sortOps` or `offset`. For the first request in a series of audit requests, leave blank. */
    timestamp?: string;
    /** Change ID provided in the previous audit response's `nextOps` attribute. An alternate way to manage response pagination. Can't be used with `sortOps` or `offset`. For the first request in a series of audit requests, leave blank. */
    changeID?: string;
}
