/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1BatchRecord {
    /** Field and value key pairs. For example, `{'field_1':'value_1', 'field_2':'value_2'}`. Only valid when `method` is `POST` or `PUT`. */
    fields?: Record<string, unknown>;
    /** Name of the table to perform the operation on. */
    tableName?: string;
    method?: Skyflow.BatchRecordMethod;
    /** ID to group operations by. Operations in the same group are executed sequentially. */
    batchID?: string;
    redaction?: Skyflow.RedactionEnumRedaction;
    /** If `true`, this operation returns tokens for fields with tokenization enabled. Only applicable if `skyflow_id` values are specified. */
    tokenization?: boolean;
    /** `skyflow_id` for the record. Only valid when `method` is `GET`, `DELETE`, or `PUT`. */
    ID?: string;
    /** If `true`, returns download URLs for fields with a file data type. URLs are valid for 15 minutes. If virus scanning is enabled, only returns if the file is clean. */
    downloadURL?: boolean;
    /** Column that stores primary keys for upsert operations. The column must be marked as unique in the vault schema. Only valid when `method` is `POST`. */
    upsert?: string;
    /** Fields and tokens for the record. For example, `{'field_1':'token_1', 'field_2':'token_2'}`. */
    tokens?: Record<string, unknown>;
}
