/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1BulkGetRecordResponse {
    /** The specified records. */
    records?: Skyflow.V1FieldRecords[];
}
