/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface V1BulkDeleteRecordResponse {
    /** IDs for the deleted records, or `*` if all records were deleted. */
    RecordIDResponse?: string[];
}
