/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Card metadata of the requested BIN.
 */
export interface V1Card {
    /** BIN of the card. */
    BIN?: string;
    /** Name of the card issuer bank. */
    issuer_name?: string;
    /** Country code of the card. */
    country_code?: string;
    /** Currency of the card. */
    currency?: string;
    /** Type of the card. */
    card_type?: string;
    /** Category of the card. */
    card_category?: string;
    /** Scheme of the card. */
    card_scheme?: string;
    /** Last four digits of the card number. */
    card_last_four_digits?: string;
    /** Expiry date of the card. */
    card_expiry?: string;
}
