/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response to deidentify a file.
 */
export interface V1DetectFileResponse {
    /** Status URL for the deidentification request. */
    status_url?: string;
}
