/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1DetokenizeRecordResponse {
    /** Token of the record. */
    token?: string;
    valueType?: Skyflow.DetokenizeRecordResponseValueType;
    /** Data corresponding to the token. */
    value?: string;
    /** Error if token isn't found. */
    error?: string;
}
