/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Response to deidentify a string.
 */
export interface V1DetectTextResponse {
    /** Deidentified text. If the input was a file, text that was extracted or transcribed from the file and deidentified. */
    processed_text?: string;
    /** Detected entities. */
    entities?: Skyflow.V1ResponseEntities[];
}
