/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface V1DeleteRecordResponse {
    /** ID of the deleted record. */
    skyflow_id?: string;
    /** If `true`, the record was deleted. */
    deleted?: boolean;
}
