/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Anti-virus scan status of the file.
 */
export type V1FileAvScanStatus =
    | "SCAN_NONE"
    | "SCAN_CLEAN"
    | "SCAN_INFECTED"
    | "SCAN_DELETED"
    | "SCAN_ERROR"
    | "SCAN_PENDING"
    | "SCAN_UNSCANNABLE"
    | "SCAN_FILE_NOT_FOUND"
    | "SCAN_INVALID";
export const V1FileAvScanStatus = {
    ScanNone: "SCAN_NONE",
    ScanClean: "SCAN_CLEAN",
    ScanInfected: "SCAN_INFECTED",
    ScanDeleted: "SCAN_DELETED",
    ScanError: "SCAN_ERROR",
    ScanPending: "SCAN_PENDING",
    ScanUnscannable: "SCAN_UNSCANNABLE",
    ScanFileNotFound: "SCAN_FILE_NOT_FOUND",
    ScanInvalid: "SCAN_INVALID",
} as const;
