/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * How to handle PDF files.
 */
export interface V1PdfOptions {
    /** Pixel density at which to process the PDF file. */
    density?: number;
    /** Max resolution at which to process the PDF file. */
    max_resolution?: number;
}
