/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1TokenizeResponse {
    /** Tokens corresponding to the specified values. */
    records?: Skyflow.V1TokenizeRecordResponse[];
}
