/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type UserServiceListUsersRequestSortOpsOrderBy = "ASCENDING" | "DESCENDING";
export const UserServiceListUsersRequestSortOpsOrderBy = {
    Ascending: "ASCENDING",
    Descending: "DESCENDING",
} as const;
