/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of the account.
 */
export type AccountAccountType = "TYPE_NONE" | "SANDBOX";
export const AccountAccountType = {
    TypeNone: "TYPE_NONE",
    Sandbox: "SANDBOX",
} as const;
