/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Regular expressions to display in plaintext. Expressions must match the entirety of a detected entity, not just a substring, for the entity to display in plaintext. Expressions don't match across entity boundaries. If a string or entity matches both `allow_regex` and `restrict_regex`, the entity is displayed in plaintext.
 */
export type AllowRegex = string[];
