/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of the resource.
 */
export type AuditEventAuditResourceType =
    | "NONE_API"
    | "ACCOUNT"
    | "AUDIT"
    | "BASE_DATA_TYPE"
    | "FIELD_TEMPLATE"
    | "FILE"
    | "KEY"
    | "POLICY"
    | "PROTO_PARSE"
    | "RECORD"
    | "ROLE"
    | "RULE"
    | "SECRET"
    | "SERVICE_ACCOUNT"
    | "TOKEN"
    | "USER"
    | "VAULT"
    | "VAULT_TEMPLATE"
    | "WORKSPACE"
    | "TABLE"
    | "POLICY_TEMPLATE"
    | "MEMBER"
    | "TAG"
    | "CONNECTION"
    | "MIGRATION"
    | "SCHEDULED_JOB"
    | "JOB"
    | "COLUMN_NAME"
    | "NETWORK_TOKEN"
    | "SUBSCRIPTION";
export const AuditEventAuditResourceType = {
    NoneApi: "NONE_API",
    Account: "ACCOUNT",
    Audit: "AUDIT",
    BaseDataType: "BASE_DATA_TYPE",
    FieldTemplate: "FIELD_TEMPLATE",
    File: "FILE",
    Key: "KEY",
    Policy: "POLICY",
    ProtoParse: "PROTO_PARSE",
    Record: "RECORD",
    Role: "ROLE",
    Rule: "RULE",
    Secret: "SECRET",
    ServiceAccount: "SERVICE_ACCOUNT",
    Token: "TOKEN",
    User: "USER",
    Vault: "VAULT",
    VaultTemplate: "VAULT_TEMPLATE",
    Workspace: "WORKSPACE",
    Table: "TABLE",
    PolicyTemplate: "POLICY_TEMPLATE",
    Member: "MEMBER",
    Tag: "TAG",
    Connection: "CONNECTION",
    Migration: "MIGRATION",
    ScheduledJob: "SCHEDULED_JOB",
    Job: "JOB",
    ColumnName: "COLUMN_NAME",
    NetworkToken: "NETWORK_TOKEN",
    Subscription: "SUBSCRIPTION",
} as const;
