/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * External authentication mode for a connected service.
 */
export type ConnectionAuthMode = "MTLS" | "NOAUTH" | "SHAREDKEY";
export const ConnectionAuthMode = {
    Mtls: "MTLS",
    Noauth: "NOAUTH",
    Sharedkey: "SHAREDKEY",
} as const;
