/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of access for the request.
 */
export type ContextAccessType = "ACCESS_NONE" | "API" | "SQL";
export const ContextAccessType = {
    AccessNone: "ACCESS_NONE",
    Api: "API",
    Sql: "SQL",
} as const;
