/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Authentication mode the `actor` used.
 */
export type ContextAuthMode = "AUTH_NONE" | "OKTA_JWT" | "SERVICE_ACCOUNT_JWT" | "PAT_JWT";
export const ContextAuthMode = {
    AuthNone: "AUTH_NONE",
    OktaJwt: "OKTA_JWT",
    ServiceAccountJwt: "SERVICE_ACCOUNT_JWT",
    PatJwt: "PAT_JWT",
} as const;
