/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Image processing options.
 */
export interface DetectConfigurationImage {
    /** If `true`, includes processed image in the output. */
    output_processed_image?: boolean;
    /** If `true`, includes OCR text output in the response. */
    output_ocr_text?: boolean;
    /** Method to mask the entities in the image. */
    masking_method?: Skyflow.DetectConfigurationImageMaskingMethod;
}
