/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface DetectConfigurationVaultFileMappingsItem {
    /** Source file table and column. */
    source_file_location?: Skyflow.DetectConfigurationVaultFileMappingsItemSourceFileLocation;
    /** De-identified file table and column. */
    deidentified_file_location?: Skyflow.DetectConfigurationVaultFileMappingsItemDeidentifiedFileLocation;
}
