/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface DetectConfigurationColumnsMappingsItem {
    entity_types?: Skyflow.EntityTypes;
    table_name?: string;
    column_name?: string;
}
