/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of transcription to output.
 */
export type DetectConfigurationAudioOutputTranscription =
    | "diarized_transcription"
    | "medical_diarized_transcription"
    | "medical_transcription"
    | "plaintext_transcription"
    | "transcription";
export const DetectConfigurationAudioOutputTranscription = {
    DiarizedTranscription: "diarized_transcription",
    MedicalDiarizedTranscription: "medical_diarized_transcription",
    MedicalTranscription: "medical_transcription",
    PlaintextTranscription: "plaintext_transcription",
    Transcription: "transcription",
} as const;
