/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface DetectConfiguration {
    vault_id?: Skyflow.VaultId;
    entity_types?: Skyflow.EntityTypes;
    token_type?: Skyflow.TokenType;
    allow_regex?: Skyflow.AllowRegex;
    restrict_regex?: Skyflow.RestrictRegex;
    transformations?: Skyflow.Transformations;
    /** Mappings between detected entities and columns in a vault. */
    columns_mappings?: Skyflow.DetectConfigurationColumnsMappingsItem[];
    /** Audio processing options. */
    audio?: Skyflow.DetectConfigurationAudio;
    /** Document processing options. */
    document?: Skyflow.DetectConfigurationDocument;
    /** Image processing options. */
    image?: Skyflow.DetectConfigurationImage;
    /** Mappings for source and de-identified file columns in a vault. */
    vault_file_mappings?: Skyflow.DetectConfigurationVaultFileMappingsItem[];
}
