/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Audio processing options.
 */
export interface DetectConfigurationAudio {
    /** If `true`, includes processed audio file in the response. */
    output_processed_audio?: boolean;
    /** Type of transcription to output. */
    output_transcription?: Skyflow.DetectConfigurationAudioOutputTranscription;
    /** Relative loudness of the bleep in dB. Positive values increase its loudness, and negative values decrease it. */
    bleep_gain?: number;
    /** The pitch of the bleep sound, in Hz. The higher the number, the higher the pitch. */
    bleep_frequency?: number;
    /** Padding added to the beginning of a bleep, in seconds. */
    bleep_start_padding?: number;
    /** Padding added to the end of a bleep, in seconds. */
    bleep_stop_padding?: number;
}
