/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Specifications for conditionally processing source data.
 */
export interface FieldMappingCondition {
    sourceField?: Skyflow.FieldMappingSourceField;
    /** Value to compare data in the source field to. */
    value?: string;
    comparator?: Skyflow.ConditionComparator;
}
