/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Host server credentials in an encrypted message.
 */
export interface FtpServerEncryptedCredentials {
    /** Encrypted message containing the server credentials. The message is a JSON object with the following fields: hostname, port, username, and password. The message must be encrypted with the same public key as the source data. */
    encryptedCredentials?: string;
}
