/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Programming languages.
 */
export type FunctionLanguageLanguageName = "LANGUAGE_NOT_DEFINED" | "NODEJS";
export const FunctionLanguageLanguageName = {
    LanguageNotDefined: "LANGUAGE_NOT_DEFINED",
    Nodejs: "NODEJS",
} as const;
