/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface ListTagsResponseTagValueConfig {
    valueName?: string;
    displayName?: string;
    displayNameV2?: string;
    description?: string;
    descriptionV2?: string;
    dataTypes?: string[];
    arrayDataTypes?: string[];
    childrenTags?: Skyflow.ListTagsResponseTagConfig[];
    version?: number;
    skyflowDataTypes?: string[];
}
