/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface ListTagsResponseTagConfig {
    tagName?: string;
    displayName?: string;
    displayNameV2?: string;
    description?: string;
    descriptionV2?: string;
    canTakeMultipleValues?: boolean;
    allowedOperations?: Skyflow.ListTagsResponseAllowedOperations;
    valueType?: string;
    values?: Skyflow.ListTagsResponseTagValueConfig[];
    dataTypes?: string[];
    arrayDataTypes?: string[];
    optional?: boolean;
}
