/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Secrets used in message encryption and signing operations.
 */
export interface MessageSecrets {
    /** Public key for encrypting messages. */
    encPublicKey?: string;
    /** Private key for encrypting messages. */
    encPrivateKey?: string;
    /** Public key for signing messages. */
    signPublicKey?: string;
    /** Private key for signing messages. */
    signPrivateKey?: string;
    /** Symmetric key for encrypting messages. */
    encSymmetricKey?: string;
    /** Symmetric key for signing messages. */
    signSymmetricKey?: string;
}
