/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * State of the pipeline run.
 *
 *  - NONE_STATE: Inactive pipeline run.
 * - INITIALIZING: Preparing the pipeline run.
 * -QUEUED: Waiting to perform the pipeline run.
 * - RUNNING: Active pipeline run.
 *  - SUCCEEDED: Successful pipeline run.
 *  - FAILED: Failed pipeline run.
 *  - STOPPED: Stopped pipeline run.
 *  - SUSPENDED: Suspended pipeline run.
 */
export type PipelineRunState =
    | "NONE_STATE"
    | "INITIALIZING"
    | "QUEUED"
    | "RUNNING"
    | "SUCCEEDED"
    | "FAILED"
    | "STOPPED"
    | "SUSPENDED";
export const PipelineRunState = {
    NoneState: "NONE_STATE",
    Initializing: "INITIALIZING",
    Queued: "QUEUED",
    Running: "RUNNING",
    Succeeded: "SUCCEEDED",
    Failed: "FAILED",
    Stopped: "STOPPED",
    Suspended: "SUSPENDED",
} as const;
