/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RelayRouteTableUpsertInfo {
    /** Name of the table to store upsert data. */
    table?: string;
    /** Name of the column used to store primary keys for upsert. */
    column?: string;
}
