/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RequestActionType =
    | "NONE"
    | "ASSIGN"
    | "CREATE"
    | "DELETE"
    | "EXECUTE"
    | "LIST"
    | "READ"
    | "UNASSIGN"
    | "UPDATE"
    | "VALIDATE"
    | "LOGIN"
    | "ROTATE"
    | "SCHEDULEROTATION"
    | "SCHEDULEROTATIONALERT"
    | "IMPORT"
    | "GETIMPORTPARAMETERS"
    | "PING"
    | "GETCLOUDPROVIDER";
export const RequestActionType = {
    None: "NONE",
    Assign: "ASSIGN",
    Create: "CREATE",
    Delete: "DELETE",
    Execute: "EXECUTE",
    List: "LIST",
    Read: "READ",
    Unassign: "UNASSIGN",
    Update: "UPDATE",
    Validate: "VALIDATE",
    Login: "LOGIN",
    Rotate: "ROTATE",
    Schedulerotation: "SCHEDULEROTATION",
    Schedulerotationalert: "SCHEDULEROTATIONALERT",
    Import: "IMPORT",
    Getimportparameters: "GETIMPORTPARAMETERS",
    Ping: "PING",
    Getcloudprovider: "GETCLOUDPROVIDER",
} as const;
