/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of the resource.
 */
export type RuleResourceType = "ACCOUNT" | "WORKSPACE" | "VAULT" | "COLUMN" | "TABLE" | "COLUMN_GROUP";
export const RuleResourceType = {
    Account: "ACCOUNT",
    Workspace: "WORKSPACE",
    Vault: "VAULT",
    Column: "COLUMN",
    Table: "TABLE",
    ColumnGroup: "COLUMN_GROUP",
} as const;
