/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Account details.
 */
export interface V1Account {
    /** Name of the account. Can only contain alphanumeric characters, and has to be unique. */
    name: string;
    /** Name of the account that displays in the user interface. */
    displayName?: string;
    /** Description of the account. */
    description?: string;
    /** Read-only. ID of the account. Generated by Skyflow. */
    ID?: string;
    /** Read-only. Namespace of the account. Generated by Skyflow. */
    namespace?: string;
    contactAddress?: Skyflow.V1Address;
    BasicAudit?: Skyflow.V1BasicAudit;
    status?: Skyflow.V1ObjectStatus;
    tenantType?: Skyflow.AccountTenantType;
    accountType?: Skyflow.AccountAccountType;
}
