/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Audit event details.
 */
export interface V1AuditResponseEvent {
    context?: Skyflow.AuditEventContext;
    request?: Skyflow.V1AuditResponseEventRequest;
    response?: Skyflow.V1AuditEventResponse;
    /** Parent account ID of the account that made the request, if any. */
    parentAccountID?: string;
    /** ID of the account that made the request. */
    accountID?: string;
    /** IDs for resources involved in the event. Presented in `{resourceType}/{resourceID}` format. For example, `VAULT/cd1d815aa09b4cbfbb803bd20349f202`. */
    resourceIDs?: string[];
}
