/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Simple audit metadata.
 */
export interface V1BasicAudit {
    /** User who created the resource. */
    CreatedBy?: string;
    /** User who last modified the resource. */
    LastModifiedBy?: string;
    /** Creation time of the resource. */
    CreatedOn?: string;
    /** Last modification time of the resource. */
    LastModifiedOn?: string;
}
