/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Column-level rule details.
 */
export interface V1ColumnRuleParams {
    /** ID of the vault that contains the column(s). */
    vaultID?: string;
    /** Column(s) that the rule applies to, specified in the format of "tableName.columnname". */
    columns?: string[];
    action?: Skyflow.V1Action;
    effect?: Skyflow.V1Effect;
    /** SQL expression that applies a filter on all rows of a table. */
    rowFilter?: string;
    /** Redaction type applied to values in the specified columns. */
    redaction?: string;
    actions?: Skyflow.V1Action[];
}
