/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface V1CreateIntegrationResponse {
    /** connection ID . */
    ID?: string;
    /** gateway URL for this connection . */
    connectionURL?: string;
}
