/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface V1CreateFunctionResponse {
    /** ID of the function. */
    ID?: string;
    /** Name of the function. */
    name?: string;
    /** Version of the function. */
    versionTag?: string;
    /** ID of the function deployment. */
    deploymentID?: string;
}
