/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Vault creation response.
 */
export interface V1CreateObjectVaultResponse {
    /** Unique ID of the Vault that was created. */
    ID?: string;
}
