/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface V1CreateFunctionEnvironmentResponse {
    /** ID of the function as which you want to create the environment. */
    functionEnvironmentID?: string;
    /** Name of the environment. */
    functionEnvironmentName?: string;
    /** Description of the environment. */
    functionEnvironmentDescription?: string;
    /** If <code>true</code>, sets the environment as the default for the account. */
    isDefault?: boolean;
}
