/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Vault data mappings.
 */
export interface V1DataMapping {
    /** Name of the table to store data in. Only applicable for pipelines that insert data into a vault. */
    tableName?: string;
    /** Column in the source data that stores a primary key. The column must be set as unique in the vault schema. Only applicable for pipelines that insert data into a vault. */
    primaryKey?: string;
    /** Mappings of source data fields to vault columns. */
    fieldMapping?: Skyflow.V1FieldMapping[];
}
