/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Vault deletion response.
 */
export interface V1DeleteObjectVaultResponse {
    /** ID of the vault. */
    ID?: string;
    /** Status of the deletion request. */
    status?: "DELETION_IN_PROGRESS";
    /** Operation ID that can be used to track the operation. */
    operationID?: string;
}
