/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Contains status of delete operation.
 */
export interface V1DeleteWorkspaceResponse {
    /** ID of the deleted Workspace. */
    ID?: string;
}
