/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1Dependency {
    language?: Skyflow.V1FunctionLanguage;
    /** Required libraries for the function. */
    whitelistedDependencies?: string[];
}
