/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * User deletion response.
 */
export interface V1DeleteUserResponse {
    /** ID of the deleted user. */
    ID?: string;
}
