/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1DeleteFunctionDeploymentResponse {
    /** ID of the deleted function deployment. */
    ID?: string;
    status?: Skyflow.V1ObjectStatus;
}
