/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response to the Delete Pipeline request.
 */
export interface V1DeletePipelineResponse {
    /** ID of the pipeline. */
    ID?: string;
}
