/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Redaction type of data.
 *
 *  - RAW: plain-text
 */
export type V1DlpFormat = "NONE_FORMAT" | "DEFAULT_FORMAT" | "RAW" | "MASKED" | "REDACTED" | "TOKENIZED";
export const V1DlpFormat = {
    NoneFormat: "NONE_FORMAT",
    DefaultFormat: "DEFAULT_FORMAT",
    Raw: "RAW",
    Masked: "MASKED",
    Redacted: "REDACTED",
    Tokenized: "TOKENIZED",
} as const;
