/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Specification for extracting values in a fixed-width file.
 */
export interface V1FixedWidthField {
    value: Skyflow.V1FixedWidthFieldValue;
    matchLines?: Skyflow.FixedWidthFieldMatchLines;
}
