/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1FunctionTagsResponse {
    /** ID of the function tag. */
    ID?: string;
    /** ID of the function. */
    functionID?: string;
    /** Version of the function. */
    versionTag?: string;
    downloadInfo?: Skyflow.V1TagDownloadInfo;
    status?: Skyflow.V1ObjectStatus;
    /** Handler configuration details. */
    handlerConfigs?: Skyflow.V1HandlerConfig[];
    BasicAudit?: Skyflow.V1BasicAudit;
    language?: Skyflow.V1FunctionLanguage;
    /** If <code>true</code, the function code is sent in a zipped file. */
    isZipped?: boolean;
    /** Required libraries for the function. */
    dependencies?: string[];
    /** Error message returned if the function tag is in a <code>FAILED</code> state. */
    errorMessage?: string;
    /** Name of the function. */
    functionName?: string;
}
