/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface V1GetFunctionDeploymentLogsResponse {
    /** ID of the function deployment. */
    ID?: string;
    /** Function deployment logs. */
    logs?: string;
}
