/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1GetMasterKeyMetadataResponse {
    /** The epoch Unix timestamp at which the Master Key was created. */
    createdAt?: string;
    /** The epoch Unix timestamp at which the Master Key will expire. Only applies for internal and non-BYOK Master Keys. */
    expiresAt?: string;
    /** The epoch Unix timestamp at which an alert will be sent to rotate the Master Key. Only applies for external and BYOK Master Keys. */
    alertAt?: string;
    /** The number of days to delay a rotation after the Master Key is created. */
    rotationPendingWindowInDays?: number;
    type?: Skyflow.V1MasterKeyType;
    origin?: Skyflow.V1MasterKeyMaterialOrigin;
    /** Unique ID of the Master Key. Only applies for external Master Keys. */
    id?: string;
    /** If `true`, a key rotation is in progress. */
    isRotationInProgress?: boolean;
}
