/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Master key import parameters.
 */
export interface V1GetMasterKeyImportResponse {
    /** Base64-encoded wrapping key. An RSA public key with which to encrypt the 256-bit AES symmetric master key. */
    publicKey?: string;
    /** Base64-encoded token used to import a master key. Valid for 24 hours. */
    importToken?: string;
    /** Region to import the master key into. */
    region?: string;
}
