/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1GetFieldTemplateResponse {
    template?: Skyflow.V1FieldTemplate;
}
