/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Response of the Get Pipeline request.
 */
export interface V1GetPipelineResponse {
    pipeline?: Skyflow.V1Pipeline;
}
