/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Response to the Get Pipeline request.
 */
export interface V1GetPipelineRunResponse {
    pipelineRun?: Skyflow.V1PipelineRun;
}
