/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1GetVaultTemplateResponse {
    template?: Skyflow.V1VaultTemplate;
}
