/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1ListFunctionTagsResponse {
    /** ID of the function. */
    functionID?: string;
    /** Name of the function. */
    functionName?: string;
    /** List all tags of the specified function. */
    tags?: Skyflow.V1TagDetail[];
}
