/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1ListIntegrationResponse {
    /** List of all connection defined for the given Vault or AccountID. */
    ConnectionMappings?: Skyflow.V1RelayMappings[];
}
