/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1ListResourcesResponse {
    /** List of all resources under the given resource. */
    resources?: Skyflow.V1Resource[];
}
