/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1ListRegionsResponse {
    /** RegionInfo with regionID as key, for the requested accountID. */
    regions?: Record<string, Skyflow.V1RegionInfo>;
}
