/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * A master key.
 */
export interface V1MasterKey {
    /** ID of the master key. */
    ID?: string;
    type?: Skyflow.V1MasterKeyType;
}
