/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of the member.
 */
export type V1MemberType = "NONE" | "USER" | "SERVICE_ACCOUNT";
export const V1MemberType = {
    None: "NONE",
    User: "USER",
    ServiceAccount: "SERVICE_ACCOUNT",
} as const;
