/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1ObjectVault {
    ID?: string;
    BasicAudit?: Skyflow.V1BasicAudit;
    name?: string;
    description?: string;
    /** Parsed Schema generated from the proto. */
    schemas?: Skyflow.V1Schema[];
    /** Namespace of the Vault. */
    namespace?: string;
    status?: Skyflow.V1ObjectStatus;
    /** Vault level Tags that are present. */
    tags?: Skyflow.V1Tag[];
    /** The json-based openapi specification for this particular vault. */
    openapiSpec?: string;
    useMasterKey?: Skyflow.V1MasterKey;
}
