/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface V1PermissionRestrictions {
    /** Name of the role to restrict. */
    roleName?: string;
    /** Permissions to remove from the specified role. */
    permissions?: string[];
}
