/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Request to stop a specified pipeline run.
 */
export type V1PipelineServiceStopPipelineRunBody = Record<string, unknown>;
