/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * PGP key used for encryption operations.
 */
export interface V1PipelinePgpKey {
    /** Private key for decryption. */
    privateKey?: string;
    /** Passphrase for decryption. */
    passphrase?: string;
    /** Public key for encryption. */
    publicKey?: string;
}
