/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1RelayRoute {
    /** Path of the route. */
    path?: string;
    /** HTTP method for the route path. */
    method?: string;
    contentType?: Skyflow.RelayRouteContentType;
    /** Operations to perform on the URL of the incoming payload. */
    url?: Skyflow.V1RelayOp[];
    /** Operations to perform on the request body of the incoming payload. */
    requestBody?: Skyflow.V1RelayOp[];
    /** Operations to perform on the response body of the incoming payload. */
    responseBody?: Skyflow.V1RelayOp[];
    /** Operations to perform on the response header of the incoming payload. */
    responseHeader?: Skyflow.V1RelayOp[];
    /** Operations to perform on the query parameters of the incoming payload. */
    queryParams?: Skyflow.V1RelayOp[];
    /** Operations to perform on the request header of the incoming payload. */
    requestHeader?: Skyflow.V1RelayOp[];
    /** Name of the route. */
    name?: string;
    /** Description of the route. */
    description?: string;
    /** SOAP action to process. */
    soapAction?: string;
    mleType?: Skyflow.RelayRouteMleType;
    /** Message-level actions to perform when Skyflow receives a request through a connection. */
    preFieldRequestMessageActions?: Skyflow.V1RelayMessageActions[];
    /** Field-level actions to perform (after message-level actions) when Skyflow receives a request through a connection. */
    postFieldRequestMessageActions?: Skyflow.V1RelayMessageActions[];
    /** Message-level actions to perform when Skyflow receives a response through a connection. */
    preFieldResponseMessageActions?: Skyflow.V1RelayMessageActions[];
    /** Field-level actions to perform (after message-level actions) when Skyflow receives a response through a connection. */
    postFieldResponseMessageActions?: Skyflow.V1RelayMessageActions[];
    /** Table and column information for upsert. */
    tableUpsertInfo?: Skyflow.RelayRouteTableUpsertInfo[];
}
