/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Resource configuration details.
 */
export interface V1ResourceConfig {
    /** Timeout for the function handler. */
    timeout?: number;
    /** Memory limit for the function handler in MBs. */
    memory?: number;
}
