/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Component of a Skyflow account.
 */
export interface V1Resource {
    /** ID of the resource. For example, if `resource.type` is `VAULT`, this field is the vault ID. If `resource.type` is `WORKSPACE`, this field is the workspace ID. */
    ID: string;
    type: Skyflow.V1ResourceType;
    /** Name of the resource. */
    name?: string;
    /** Unique namespace for the resource. Generated by Skyflow. */
    namespace?: string;
    /** Description of the resource. */
    description?: string;
    status?: Skyflow.V1ObjectStatus;
    /** Display name of the resource that appears in user interfaces. */
    displayName?: string;
}
