/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 *  - QUEUED: value for async implementation.
 *  - DONE: value for synchronous implementation (current) can be removed when all env is async.
 */
export type V1RotateMasterKeyStatus = "INVALID_RMKS" | "QUEUED" | "DONE";
export const V1RotateMasterKeyStatus = {
    InvalidRmks: "INVALID_RMKS",
    Queued: "QUEUED",
    Done: "DONE",
} as const;
