/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Schema that represents the fields and field options of the vault.
 */
export interface V1Schema {
    /** ID of the schema. */
    ID?: string;
    /** Name of the schema. */
    name?: string;
    parentSchemaProperties?: Skyflow.V1ParentSchemaProperties;
    /** Fields in this schema. */
    fields?: Skyflow.V1Field[];
    /** Complete `schema` objects contained within the current schema. */
    childrenSchemas?: Skyflow.V1SchemaChildrenSchemasItem[];
    /** Tags applied to a schema. */
    schemaTags?: Skyflow.V1Tag[];
    properties?: Skyflow.V1Properties;
}
