/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1StsConfig {
    ID?: string;
    name?: string;
    description?: string;
    issuer?: string;
    /** Public key as JWK endpoint */
    publicKeyJWKURI?: string;
    /** list of service account IDs; */
    serviceAccountIDs?: string[];
    contextClaims?: string[];
    accountID?: string;
    namespace?: string;
    BasicAudit?: Skyflow.V1BasicAudit;
}
