/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface V1Tag {
    /** Name of the tag. For a reference of available tags, see <a href='/vault-settings/'>Vault settings</a>. */
    name?: string;
    /** Array of values for the tag. */
    values?: string[];
}
