/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Info about TokenRequestor.
 */
export interface V1TokenRequestorInfo {
    /** The legal name of the Token Requestor. This must be unique.Ohterwise, it will result in request rejection. */
    tokenRequestorLegalName?: string;
    /** First line of the Token Requestor's primary address. */
    address1?: string;
    /** Second line of the Token Requestor's primary address. It can be empty. */
    address2?: string;
    /** Indication if the token requestor supports debit cards, credit cards or both.It is required for MDES, otherwise, it is optional. */
    cardTypeIndicator?: string;
    /** City in the Token Requestor's primary address. It is required for VTS, otherwise, it is optional. */
    city?: string;
    /** Email address of Token Requestor's primary contact. It is required for VTS, otherwise, it is optional. */
    contactEmail?: string;
    /** First name of Token Requestor's primary contact person. */
    contactFirstName?: string;
    /** Surname of Token Requestor's primary contact person. */
    contactLastName?: string;
    /** Token Requestor's primary contact number. */
    contactNumber?: string;
    /** ISO-3166-1 alpha-2 standard country associated with the Token Requestor's primary address. It is required for VTS, otherwise, it is optional. */
    countryCode?: string;
    /** Dun & Bradstreet assigned D-U-N-S Number for this Token Requestor. */
    dunsNumber?: string;
    /** Postal code associated with the primary address of Token Requestor, such as a ZIP code. */
    postalCode?: string;
    /** Trade name of Token Requestor, such as a doingbusiness-as (DBA) name. If not specified, the tokenRequestorName is used by default. */
    primaryTradeName?: string;
    /** Token Requestor's URL for handling Visa SRC transactions. It is required for VTS, otherwise, it is optional. */
    primaryWebsiteURL?: string;
    /** State or province code associated with the physical address in the specified country. */
    stateProvinceCode?: string;
    /** The logo of the token requestor in a PNG format. */
    tokenRequestorPngLogo?: string;
    /** The logo of the token requestor in a PNG format. The base64 encoded binary of the image. The dimensions must be square. */
    tokenRequestorSvgLogo?: string;
}
