/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Visa Token Requestor's business identifier.
 */
export interface V1TokenRequestorBusinessIdentifier {
    /** The prefix indicates the type is applicable for which scheme TSP. */
    type?: string;
    /** The value of the provided type. */
    value?: string;
}
