/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Vault update response.
 */
export interface V1UpdateObjectVaultResponse {
    /** ID of the updated Vault. */
    ID?: string;
}
