/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of the variable.
 */
export type V1UpdateFunctionEnvironmentVariableRequestEnvironmentVariableType = "NONE" | "PLAIN_TEXT" | "SECRET";
export const V1UpdateFunctionEnvironmentVariableRequestEnvironmentVariableType = {
    None: "NONE",
    PlainText: "PLAIN_TEXT",
    Secret: "SECRET",
} as const;
