/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Identity information of the user.
 */
export interface V1UserIdentity {
    /** Email address of the user. */
    email?: string;
    /** Okta ID of the user. */
    oktaID?: string;
}
