/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * User details.
 */
export interface V1User {
    /** Name of the user. */
    name?: string;
    contactAddress?: Skyflow.V1Address;
    userIdentity: Skyflow.V1UserIdentity;
    /** ID of the user. Generated by Skyflow. */
    ID?: string;
    status?: Skyflow.V1ObjectStatus;
    BasicAudit?: Skyflow.V1BasicAudit;
}
