/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

/**
 * Business identifications of the Token Requestor.
 */
export interface V1VisaBusinessIdentifications {
    tokenRequestorBusinessIdentifier?: Skyflow.V1TokenRequestorBusinessIdentifier;
    /** List of identifiers associated with the Token Requestor's acquirers. It is required if tokenRequestorBusinessIdentifier is not present. */
    acquirerIdentifiers?: Skyflow.V1AcquirerIdentifier[];
}
