/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../index";

export interface V1WorkspaceLimits {
    /** Maximum number of vaults. */
    vaultCountLimit?: string;
    /** Maximum size of a vault. */
    vaultSizeLimit?: string;
    /** Maximum number of owners for a vault. */
    vaultOwnerLimit?: string;
    /** Permissions removed from specified roles. */
    permissionRestrictions?: Skyflow.V1PermissionRestrictions[];
    /** Identifier for whether vaults can be shared externally. */
    enableExternalSharing?: boolean;
}
