/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of the workspace.
 */
export type WorkspaceWorkspaceType = "NONE_TYPE" | "SANDBOX" | "PRODUCTION";
export const WorkspaceWorkspaceType = {
    NoneType: "NONE_TYPE",
    Sandbox: "SANDBOX",
    Production: "PRODUCTION",
} as const;
