/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         resourceType: "NONE"
 *     }
 */
export interface RoleServiceListRoleDefinitionsRequest {
    /**
     * Filter that limits results to those that match the specified type.
     */
    resourceType?: Skyflow.RoleServiceListRoleDefinitionsRequestResourceType;
}
