/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         "filterOps.email": "filterOps.email",
 *         "filterOps.type": "NONE",
 *         "filterOps.name": "filterOps.name",
 *         "filterOps.status": "NONE",
 *         "sortOps.sortBy": "sortOps.sortBy",
 *         "sortOps.orderBy": "ASCENDING",
 *         offset: "offset",
 *         limit: "limit"
 *     }
 */
export interface RoleServiceListMembersByRoleRequest {
    /**
     * Filter that limits results to those that match the specified email address.
     */
    "filterOps.email"?: string;
    /**
     * Filter that limits results to those that match the specified type.
     */
    "filterOps.type"?: Skyflow.RoleServiceListMembersByRoleRequestFilterOpsType;
    /**
     * Filter that limits results to those that match the specified name.
     */
    "filterOps.name"?: string;
    /**
     * Filter that limits results to those that match the specified status.
     */
    "filterOps.status"?: Skyflow.RoleServiceListMembersByRoleRequestFilterOpsStatus;
    /**
     * Fully-qualified field by which to sort results. Field names should be in camel case (for example, "capitalization.camelCase").
     */
    "sortOps.sortBy"?: string;
    /**
     * Ascending or descending ordering of results.
     */
    "sortOps.orderBy"?: Skyflow.RoleServiceListMembersByRoleRequestSortOpsOrderBy;
    /**
     * Record position at which to start receiving results.
     */
    offset?: string;
    /**
     * Number of results to return.
     */
    limit?: string;
}
