/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         accountID: "accountID",
 *         "filterOps.name": "filterOps.name",
 *         "filterOps.status": "NONE",
 *         "sortOps.sortBy": "sortOps.sortBy",
 *         "sortOps.orderBy": "ASCENDING",
 *         offset: 1000000,
 *         limit: 1000000
 *     }
 */
export interface VaultTemplateServiceListVaultTemplatesRequest {
    /**
     * ID of the account.
     */
    accountID: string;
    /**
     * Filter that limits results to those that match the specified name.
     */
    "filterOps.name"?: string;
    /**
     * Filter that limits results to those that match the specified status.
     */
    "filterOps.status"?: Skyflow.VaultTemplateServiceListVaultTemplatesRequestFilterOpsStatus;
    /**
     * Fully-qualified field by which to sort results. Field names should be in camel case (for example, "capitalization.camelCase").
     */
    "sortOps.sortBy"?: string;
    /**
     * Ascending or descending ordering of results.
     */
    "sortOps.orderBy"?: Skyflow.VaultTemplateServiceListVaultTemplatesRequestSortOpsOrderBy;
    /**
     * Record position at which to start receiving results.
     */
    offset?: number;
    /**
     * Number of results to return.
     */
    limit?: number;
}
