/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AuditServiceListAuditEventsRequestFilterOpsContextAccessType = "ACCESS_NONE" | "API" | "SQL" | "OKTA_LOGIN";
export const AuditServiceListAuditEventsRequestFilterOpsContextAccessType = {
    AccessNone: "ACCESS_NONE",
    Api: "API",
    Sql: "SQL",
    OktaLogin: "OKTA_LOGIN",
} as const;
