/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ServiceAccountServiceListServiceAccountsRequestStatus =
    | "NONE"
    | "CREATED"
    | "PENDING"
    | "ACTIVE"
    | "INACTIVE"
    | "ARCHIVED"
    | "DELETED";
export const ServiceAccountServiceListServiceAccountsRequestStatus = {
    None: "NONE",
    Created: "CREATED",
    Pending: "PENDING",
    Active: "ACTIVE",
    Inactive: "INACTIVE",
    Archived: "ARCHIVED",
    Deleted: "DELETED",
} as const;
