/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         detokenizationParameters: [{
 *                 token: "afbd1074-51c1-4a16-9eee-e2c0ecb52125",
 *                 redaction: "PLAIN_TEXT"
 *             }, {
 *                 token: "05383487-fcae-42e5-a48e-5bd62a51af12",
 *                 redaction: "DEFAULT"
 *             }],
 *         downloadURL: false
 *     }
 */
export interface V1DetokenizePayload {
    /** Detokenization details. */
    detokenizationParameters?: Skyflow.V1DetokenizeRecordRequest[];
    /** If `true`, returns download URLs for fields with a file data type. URLs are valid for 15 minutes. If virus scanning is enabled, only returns if the file is clean. */
    downloadURL?: boolean;
    /** If `true`, the detokenization request continues even if an error occurs. */
    continueOnError?: boolean;
}
