/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         vault_id: "f4b3b3b33b3b3b3b3b3b3b3b3b3b3b3b",
 *         file: {
 *             base64: "Zm9vYmFy",
 *             data_format: "txt"
 *         }
 *     }
 *
 * @example
 *     {
 *         vault_id: "VAULT_ID",
 *         file: {
 *             base64: "Zm9vYmFy",
 *             data_format: "txt"
 *         }
 *     }
 */
export interface DeidentifyTextRequest {
    vault_id: Skyflow.VaultId;
    /** File to de-identify. Files are specified as Base64-encoded data. */
    file: Skyflow.DeidentifyTextRequestFile;
    entity_types?: Skyflow.EntityTypes;
    token_type?: Skyflow.TokenTypeWithoutVault;
    allow_regex?: Skyflow.AllowRegex;
    restrict_regex?: Skyflow.RestrictRegex;
    transformations?: Skyflow.Transformations;
}
