/* tslint:disable */
/* eslint-disable */
/**
 * Skyflow Data API
 * # Data API  This API inserts, retrieves, and otherwise manages data in a vault.  The Data API is available from two base URIs. *identifier* is the identifier in your vault\'s URL.<ul><li><b>Sandbox:</b> https://_*identifier*.vault.skyflowapis-preview.com</li><li><b>Production:</b> https://_*identifier*.vault.skyflowapis.com</li></ul>  When you make an API call, you need to add a header: <table><tr><th>Header</th><th>Value</th><th>Example</th></tr><tr><td>Authorization</td><td>A Bearer Token. See <a href=\'/api-authentication/\'>API Authentication</a>.</td><td><code>Authorization: Bearer eyJhbGciOiJSUzI...1NiIsJdfPA</code></td></tr><table/>
 *
 * The version of the OpenAPI document: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1BYOT } from './v1-byot';
// May contain unused imports in some cases
// @ts-ignore
import type { V1FieldRecords } from './v1-field-records';

/**
 * 
 * @export
 * @interface RecordServiceInsertRecordBody
 */
export interface RecordServiceInsertRecordBody {
    /**
     * Record values and tokens.
     * @type {Array<V1FieldRecords>}
     * @memberof RecordServiceInsertRecordBody
     */
    'records'?: Array<V1FieldRecords>;
    /**
     * If `true`, this operation returns tokens for fields with tokenization enabled.
     * @type {boolean}
     * @memberof RecordServiceInsertRecordBody
     */
    'tokenization'?: boolean;
    /**
     * Name of a unique column in the table. Uses upsert operations to check if a record exists based on the unique column\'s value. If a matching record exists, the record updates with the values you provide. If a matching record doesn\'t exist, the upsert operation inserts a new record.<br /><br />When you upsert a field, include the entire contents you want the field to store. For JSON fields, include all nested fields and values. If a nested field isn\'t included, it\'s removed.
     * @type {string}
     * @memberof RecordServiceInsertRecordBody
     */
    'upsert'?: string;
    /**
     * If `true`, this operation mandates that all the records have the same fields. This parameter does not work with upsert.
     * @type {boolean}
     * @memberof RecordServiceInsertRecordBody
     */
    'homogeneous'?: boolean;
    /**
     * 
     * @type {V1BYOT}
     * @memberof RecordServiceInsertRecordBody
     */
    'byot'?: V1BYOT;
}



