/* tslint:disable */
/* eslint-disable */
/**
 * Skyflow Data API
 * # Data API  This API inserts, retrieves, and otherwise manages data in a vault.  The Data API is available from two base URIs. *identifier* is the identifier in your vault\'s URL.<ul><li><b>Sandbox:</b> https://_*identifier*.vault.skyflowapis-preview.com</li><li><b>Production:</b> https://_*identifier*.vault.skyflowapis.com</li></ul>  When you make an API call, you need to add a header: <table><tr><th>Header</th><th>Value</th><th>Example</th></tr><tr><td>Authorization</td><td>A Bearer Token. See <a href=\'/api-authentication/\'>API Authentication</a>.</td><td><code>Authorization: Bearer eyJhbGciOiJSUzI...1NiIsJdfPA</code></td></tr><table/>
 *
 * The version of the OpenAPI document: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Record values and tokens.
 * @export
 * @interface V1FieldRecords
 */
export interface V1FieldRecords {
    /**
     * Fields and values for the record. For example, `{\'field_1\':\'value_1\', \'field_2\':\'value_2\'}`.
     * @type {object}
     * @memberof V1FieldRecords
     */
    'fields'?: object;
    /**
     * Fields and tokens for the record. For example, `{\'field_1\':\'token_1\', \'field_2\':\'token_2\'}`.
     * @type {object}
     * @memberof V1FieldRecords
     */
    'tokens'?: object;
}

