/* tslint:disable */
/* eslint-disable */
/**
 * Skyflow Data API
 * # Data API  This API inserts, retrieves, and otherwise manages data in a vault.  The Data API is available from two base URIs. *identifier* is the identifier in your vault\'s URL.<ul><li><b>Sandbox:</b> https://_*identifier*.vault.skyflowapis-preview.com</li><li><b>Production:</b> https://_*identifier*.vault.skyflowapis.com</li></ul>  When you make an API call, you need to add a header: <table><tr><th>Header</th><th>Value</th><th>Example</th></tr><tr><td>Authorization</td><td>A Bearer Token. See <a href=\'/api-authentication/\'>API Authentication</a>.</td><td><code>Authorization: Bearer eyJhbGciOiJSUzI...1NiIsJdfPA</code></td></tr><table/>
 *
 * The version of the OpenAPI document: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Anti-virus scan status of the file.
 * @export
 * @enum {string}
 */

export const V1FileAVScanStatus = {
    None: 'SCAN_NONE',
    Clean: 'SCAN_CLEAN',
    Infected: 'SCAN_INFECTED',
    Deleted: 'SCAN_DELETED',
    Error: 'SCAN_ERROR',
    Pending: 'SCAN_PENDING',
    Unscannable: 'SCAN_UNSCANNABLE',
    FileNotFound: 'SCAN_FILE_NOT_FOUND',
    Invalid: 'SCAN_INVALID'
} as const;

export type V1FileAVScanStatus = typeof V1FileAVScanStatus[keyof typeof V1FileAVScanStatus];



