/* tslint:disable */
/* eslint-disable */
/**
 * Skyflow Management API
 * # Management API  This API controls aspects of your account and schema, including workspaces, vaults, keys, users, permissions, and more.  The Management API is available from two base URIs:<ul><li><b>Sandbox:</b> https://manage.skyflowapis-preview.com</li><li><b>Production:</b> https://manage.skyflowapis.com</li></ul>  When you make an API call, you need to add two headers: <table><tr><th>Header</th><th>Value</th><th>Example</th></tr><tr><td>Authorization</td><td>A Bearer Token. See <a href=\'/api-authentication/\'>API Authentication</a>.</td><td><code>Authorization: Bearer eyJhbGciOiJSUzI...1NiIsJdfPA</code></td></tr><tr><td>X-SKYFLOW-ACCOUNT-ID</td><td>Your Skyflow account ID.</td><td><code>X-SKYFLOW-ACCOUNT-ID: h451b763713e4424a7jke1bbkbbc84ef</code></td></tr><table/>
 *
 * The version of the OpenAPI document: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1GetAuthTokenRequest
 */
export interface V1GetAuthTokenRequest {
    /**
     * Grant type of the request. Set this to `urn:ietf:params:oauth:grant-type:jwt-bearer`.
     * @type {string}
     * @memberof V1GetAuthTokenRequest
     */
    'grant_type': string;
    /**
     * User-signed JWT token that contains the following fields: <br/> <ul><li><code>iss</code>: Issuer of the JWT.</li><li><code>key</code>: Unique identifier for the key.</li><li><code>aud</code>: Recipient the JWT is intended for.</li><li><code>exp</code>: Time the JWT expires.</li><li><code>sub</code>: Subject of the JWT.</li><li><code>ctx</code>: (Optional) Value for <a href=\'/context-aware-overview/\'>Context-aware authorization</a>.</li></ul>
     * @type {string}
     * @memberof V1GetAuthTokenRequest
     */
    'assertion': string;
    /**
     * Subject token.
     * @type {string}
     * @memberof V1GetAuthTokenRequest
     */
    'subject_token'?: string;
    /**
     * Subject token type.
     * @type {string}
     * @memberof V1GetAuthTokenRequest
     */
    'subject_token_type'?: string;
    /**
     * Token use type. Either `delegation` or `impersonation`.
     * @type {string}
     * @memberof V1GetAuthTokenRequest
     */
    'requested_token_use'?: string;
    /**
     * Subset of available <a href=\'#Roles\'>roles</a> to associate with the requested token. Uses the format \"role:\\<roleID1\\> role:\\<roleID2\\>\".
     * @type {string}
     * @memberof V1GetAuthTokenRequest
     */
    'scope'?: string;
}

