/* tslint:disable */
/* eslint-disable */
/**
 * Skyflow Data API
 * # Data API  This API inserts, retrieves, and otherwise manages data in a vault.  The Data API is available from two base URIs. *identifier* is the identifier in your vault\'s URL.<ul><li><b>Sandbox:</b> https://_*identifier*.vault.skyflowapis-preview.com</li><li><b>Production:</b> https://_*identifier*.vault.skyflowapis.com</li></ul>  When you make an API call, you need to add a header: <table><tr><th>Header</th><th>Value</th><th>Example</th></tr><tr><td>Authorization</td><td>A Bearer Token. See <a href=\'/api-authentication/\'>API Authentication</a>.</td><td><code>Authorization: Bearer eyJhbGciOiJSUzI...1NiIsJdfPA</code></td></tr><table/>
 *
 * The version of the OpenAPI document: v1
 * Contact: support@skyflow.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { V1VaultFieldMapping } from './v1-vault-field-mapping';

/**
 * Details of the vault that stores additional card details.
 * @export
 * @interface V1VaultSchemaConfig
 */
export interface V1VaultSchemaConfig {
    /**
     * ID of the vault that stores card details.
     * @type {string}
     * @memberof V1VaultSchemaConfig
     */
    'id'?: string;
    /**
     * Name of the table that stores card details.
     * @type {string}
     * @memberof V1VaultSchemaConfig
     */
    'table_name'?: string;
    /**
     * 
     * @type {V1VaultFieldMapping}
     * @memberof V1VaultSchemaConfig
     */
    'mapping'?: V1VaultFieldMapping;
}

