/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Skyflow from "../../../index";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index";

export declare namespace Guardrails {
    export interface Options {
        environment?: core.Supplier<environments.SkyflowEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        token: core.Supplier<core.BearerToken>;
        fetcher?: core.FetchFunction;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}

export class Guardrails {
    constructor(protected readonly _options: Guardrails.Options) {}

    /**
     * Preserve safety and compliance with usage policies.
     *
     * @param {Skyflow.CheckGuardrailsRequest} request
     * @param {Guardrails.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Skyflow.BadRequestError}
     * @throws {@link Skyflow.UnauthorizedError}
     * @throws {@link Skyflow.InternalServerError}
     *
     * @example
     *     await client.guardrails.checkGuardrails({
     *         vault_id: "VAULT_ID",
     *         text: "I love to play cricket.",
     *         check_toxicity: true,
     *         deny_topics: ["sports"]
     *     })
     */
    public checkGuardrails(
        request: Skyflow.CheckGuardrailsRequest,
        requestOptions?: Guardrails.RequestOptions,
    ): core.HttpResponsePromise<Skyflow.CheckGuardrailsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__checkGuardrails(request, requestOptions));
    }

    private async __checkGuardrails(
        request: Skyflow.CheckGuardrailsRequest,
        requestOptions?: Guardrails.RequestOptions,
    ): Promise<core.WithRawResponse<Skyflow.CheckGuardrailsResponse>> {
        const _response = await (this._options.fetcher ?? core.fetcher)({
            url: urlJoin(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.SkyflowEnvironment.Production,
                "v1/detect/guardrails",
            ),
            method: "POST",
            headers: {
                Authorization: await this._getAuthorizationHeader(),
                "X-Fern-Language": "JavaScript",
                "X-Fern-SDK-Name": "skyflow",
                "X-Fern-SDK-Version": "1.0.21",
                "User-Agent": "skyflow/1.0.21",
                "X-Fern-Runtime": core.RUNTIME.type,
                "X-Fern-Runtime-Version": core.RUNTIME.version,
                ...requestOptions?.headers,
            },
            contentType: "application/json",
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Skyflow.CheckGuardrailsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Skyflow.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Skyflow.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Skyflow.InternalServerError(
                        _response.error.body as Skyflow.ErrorResponse,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.SkyflowError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.SkyflowError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.SkyflowTimeoutError("Timeout exceeded when calling POST /v1/detect/guardrails.");
            case "unknown":
                throw new errors.SkyflowError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string> {
        return `Bearer ${await core.Supplier.get(this._options.token)}`;
    }
}
