/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Data format of the file.
 */
export type DeidentifyFileRequestFileDataFormat =
    | "bmp"
    | "csv"
    | "dcm"
    | "doc"
    | "docx"
    | "jpeg"
    | "jpg"
    | "json"
    | "mp3"
    | "pdf"
    | "png"
    | "ppt"
    | "pptx"
    | "tif"
    | "tiff"
    | "txt"
    | "wav"
    | "xls"
    | "xlsx"
    | "xml";
export const DeidentifyFileRequestFileDataFormat = {
    Bmp: "bmp",
    Csv: "csv",
    Dcm: "dcm",
    Doc: "doc",
    Docx: "docx",
    Jpeg: "jpeg",
    Jpg: "jpg",
    Json: "json",
    Mp3: "mp3",
    Pdf: "pdf",
    Png: "png",
    Ppt: "ppt",
    Pptx: "pptx",
    Tif: "tif",
    Tiff: "tiff",
    Txt: "txt",
    Wav: "wav",
    Xls: "xls",
    Xlsx: "xlsx",
    Xml: "xml",
} as const;
