/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Method to mask the entities in the image.
 */
export type DeidentifyImageRequestMaskingMethod = "blackbox" | "blur";
export const DeidentifyImageRequestMaskingMethod = {
    Blackbox: "blackbox",
    Blur: "blur",
} as const;
