/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Method to mask the entities in the image.
 */
export type DeidentifyImageRequestMaskingMethod = "blackout" | "blur";
export const DeidentifyImageRequestMaskingMethod = {
    Blackout: "blackout",
    Blur: "blur",
} as const;
