/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../index";

/**
 * Mapping of preferred data formatting options to entity types. Returned values are dependent on the configuration of the vault storing the data and the permissions of the user or account making the request.
 */
export interface ReidentifyFileRequestFormat {
    /** Entity types to fully redact. */
    redacted?: Skyflow.EntityType[];
    /** Entity types to mask. */
    masked?: Skyflow.EntityType[];
    /** Entity types to return in plaintext. */
    plaintext?: Skyflow.EntityType[];
}
