/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PipelineServiceListPipelinesRequestSortOpsOrderBy = "ASCENDING" | "DESCENDING";
export const PipelineServiceListPipelinesRequestSortOpsOrderBy = {
    Ascending: "ASCENDING",
    Descending: "DESCENDING",
} as const;
