/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type PipelineServiceListPipelineRunsRequestFilterOpsState =
    | "NONE_STATE"
    | "RUNNING"
    | "SUCCEEDED"
    | "FAILED"
    | "STOPPED"
    | "SUSPENDED";
export const PipelineServiceListPipelineRunsRequestFilterOpsState = {
    NoneState: "NONE_STATE",
    Running: "RUNNING",
    Succeeded: "SUCCEEDED",
    Failed: "FAILED",
    Stopped: "STOPPED",
    Suspended: "SUSPENDED",
} as const;
