/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type AuditServiceListAuditEventsRequestFilterOpsContextActorType = "NONE" | "USER" | "SERVICE_ACCOUNT";
export const AuditServiceListAuditEventsRequestFilterOpsContextActorType = {
    None: "NONE",
    User: "USER",
    ServiceAccount: "SERVICE_ACCOUNT",
} as const;
