/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as errors from "../../errors/index";
import * as Skyflow from "../index";
import * as core from "../../core";

export class InternalServerError extends errors.SkyflowError {
    constructor(body: Skyflow.ErrorResponse, rawResponse?: core.RawResponse) {
        super({
            message: "InternalServerError",
            statusCode: 500,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, InternalServerError.prototype);
    }
}
