/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Skyflow from "../../../../index";

/**
 * @example
 *     {
 *         workspaceID: "tempor",
 *         masterKey: {
 *             ID: "aliqua in",
 *             type: "INVALID"
 *         },
 *         pendingWindowInDays: 0,
 *         rotationReminderRecipients: [{
 *                 name: "anim cupidatat in Ut",
 *                 email: "aute cupidatat irure dolore"
 *             }, {
 *                 name: "elit laboris an",
 *                 email: "aliquip ex ea consequat laboris"
 *             }, {
 *                 name: "sunt in cillum laboris dolore",
 *                 email: "esse"
 *             }]
 *     }
 */
export interface ObjectVaultServiceRotateMasterKeyBody {
    /** ID of the worspace that contains the vault. */
    workspaceID?: string;
    masterKey?: Skyflow.V1MasterKey;
    /** Number of days to wait before rotating keys. If not specified, rotation happens immediately. */
    pendingWindowInDays?: number;
    /** Recipients of rotation reminders. Applicable only when <code>pendingWindowInDays</code> doesn't equal <code>0</code>. If not specified, the default user for the account receives rotation reminders. */
    rotationReminderRecipients?: Skyflow.V1Contact[];
}
