/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         workspaceID: "workspaceID",
 *         primaryRegionImportToken: "primaryRegionImportToken"
 *     }
 */
export interface ObjectVaultServiceGetMasterKeyImportParamsRequest {
    /**
     * ID of the workspace.
     */
    workspaceID?: string;
    /**
     * The import token for the master key on the primary region. Required only when requesting import parameters for a replica region.
     */
    primaryRegionImportToken?: string;
}
