/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RoleServiceListRolesRequestSortOpsOrderBy = "ASCENDING" | "DESCENDING";
export const RoleServiceListRolesRequestSortOpsOrderBy = {
    Ascending: "ASCENDING",
    Descending: "DESCENDING",
} as const;
