/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RoleServiceListRolesRequestType = "NONE" | "SYSTEM" | "CUSTOM";
export const RoleServiceListRolesRequestType = {
    None: "NONE",
    System: "SYSTEM",
    Custom: "CUSTOM",
} as const;
